
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							SPONTANEOUS CASTING FUNCTION
//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION fnp_spontaneous STR_VAR kit_clab = ~x~ learn_res = ~d5msham~ free_universal = ~yes~ BEGIN

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5fpspt.spl~) BEGIN
  COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5fpspt.spl~
	SAY NAME1 @49917
	SAY UNIDENTIFIED_DESC @49918
	WRITE_SHORT 0x1c 4
//	LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5fpsp3.spl~
	SAY NAME1 @49917
	SAY UNIDENTIFIED_DESC @49918
	LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~d5lernpr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5fpspt~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5fpsp2.spl~) BEGIN
  COPY ~faiths_and_powers/kits/misc/d5msplbk.bam~ ~override~
  COPY ~faiths_and_powers/kits/misc/d5lernpr.bam~ ~override~
  COPY ~faiths_and_powers/kits/misc/d5lernwi.bam~ ~override~
  COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5fpsp2.spl~
	SAY NAME1 @49917
	SAY UNIDENTIFIED_DESC @49918
	LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~d5msplbk~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 0 duration = 7 STR_VAR resource = ~d5fpsp2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = ~d5fpsp2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5fpsp2~ END
  COPY ~faiths_and_powers/kits/misc/d5fpsp2.eff~ ~override~
  COPY ~faiths_and_powers/kits/misc/d5fpsp2.cre~ ~override~
  COMPILE ~faiths_and_powers/kits/misc/d5fpsp2.baf~
  COMPILE ~faiths_and_powers/kits/misc/d5fpsp2.d~
END

// ***** the free_universal variable won't quite work yet if you set it to 'no'
// in that case, need to add those spells to the kit's learnable list, and remove them from the spellbook

INCLUDE ~faiths_and_powers/lib/sequencer_menu_d5.tpa~

COPY_EXISTING ~kitlist.2da~ ~override~
  COUNT_2DA_ROWS 10 rows
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY row 5 10 clab
	PATCH_IF (~%clab%~ STRING_EQUAL_CASE ~%kit_clab%~) BEGIN
	  READ_2DA_ENTRY row 8 10 kit_class
	  READ_2DA_ENTRY row 9 10 kit_ids
	END
  END
BUT_ONLY

ACTION_IF !(IS_AN_INT %kit_class%) BEGIN
  OUTER_SET kit_class = 21
END

PRINT ~the class for this kit is: %kit_class%~

ACTION_IF (d5_spell_spontaneous = 0) BEGIN
  COPY_EXISTING ~d5_class.2da~ ~override~
	COUNT_2DA_ROWS 4 rows
	FOR (row = 0; row < rows; row += 1) BEGIN
	  READ_2DA_ENTRY row 0 4 kit
	  PATCH_IF (~%kit%~ STRING_EQUAL_CASE ~%kit_clab%~) BEGIN
		SET_2DA_ENTRY row 1 4 ~MYSTIC~
	  END
	END
  BUT_ONLY
END

ACTION_IF (VARIABLE_IS_SET %kit_ids%) BEGIN
  APPEND ~splprot.2da~ ~D5_KIT_IS%TAB%152%TAB%-1%TAB%1~ UNLESS ~D5_KIT_IS~
  COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_KIT_IS~ BEGIN
	    SET kit_is_row = %row%
	  END
	END
  BUT_ONLY
END
ACTION_IF !(VARIABLE_IS_SET %kit_ids%) BEGIN
  OUTER_SET kit_is_row = 105
  OUTER_SET kit_ids = 21
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5_shmkn.2da~) BEGIN
  COPY ~faiths_and_powers/kits/misc/d5_shmkn.2da~ ~override~
  COPY ~faiths_and_powers/kits/misc/splshmkn.2da~ ~override~
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5_rpkn.2da~) BEGIN
  COPY ~faiths_and_powers/kits/misc/d5_rpkn.2da~ ~override~
END

//semi spont spellstate_______________________________________________________________
//
ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SPONT_DIVINE~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_SPONT_DIVINE~) BEGIN
		SET spont_divine_state = %state_ind%
	  END
	END
  BUT_ONLY
END
/*
ACTION_IF !(FILE FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SPONT_DIVINE~)) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_SPONT_DIVINE~ RET new_state_ind END
  OUTER_SET spont_divine_state = %new_state_ind%
END
*/
ACTION_IF !(VARIABLE_IS_SET %spont_divine_state%) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_SPONT_DIVINE~ RET new_state_ind END
  OUTER_SET spont_divine_state = %new_state_ind%
END

// create learnable spell list - sphere system________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5_spheres.d5~) BEGIN

 ACTION_IF !(~%kit_clab%~ STRING_EQUAL_CASE ~x~) BEGIN

  <<<<<<<<  d5/d5spontlist.2da
2DA V1.0
****
            	     ResRef   Type>>>>>>>>
  COPY ~d5/d5spontlist.2da~ ~override/%learn_res%.2da~

  COPY_EXISTING ~d5_spher.2da~ ~override~
	COUNT_2DA_COLS cols
	COUNT_2DA_ROWS cols rows
	FOR (row = 0; row < rows; row += 1) BEGIN
	  READ_2DA_ENTRY row 0 cols sph_kit
	  PATCH_IF (~%sph_kit%~ STRING_EQUAL_CASE ~%kit_clab%~) BEGIN
        READ_2DA_ENTRY row 1 cols lif
        PATCH_IF (~%lif%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~plif~) ~1~
        END
        PATCH_IF (~%lif%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mlif~) ~1~
        END
        PATCH_IF (~%lif%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~lif~) ~focus~
        END
        READ_2DA_ENTRY row 2 cols dea
        PATCH_IF (~%dea%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~pdea~) ~1~
        END
        PATCH_IF (~%dea%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mdea~) ~1~
        END
        PATCH_IF (~%dea%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~dea~) ~focus~
        END
        READ_2DA_ENTRY row 3 cols cre
        PATCH_IF (~%cre%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~pben~) ~1~
        END
        PATCH_IF (~%cre%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mben~) ~1~
        END
        PATCH_IF (~%cre%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~cre~) ~focus~
        END
        READ_2DA_ENTRY row 4 cols des
        PATCH_IF (~%des%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~pdes~) ~1~
        END
        PATCH_IF (~%des%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mdes~) ~1~
        END
        PATCH_IF (~%des%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~des~) ~focus~
        END
        READ_2DA_ENTRY row 5 cols pro
        PATCH_IF (~%pro%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~ppro~) ~1~
        END
        PATCH_IF (~%pro%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mpro~) ~1~
        END
        PATCH_IF (~%pro%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~pro~) ~focus~
        END
        READ_2DA_ENTRY row 6 cols war
        PATCH_IF (~%war%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~pwar~) ~1~
        END
        PATCH_IF (~%war%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mwar~) ~1~
        END
        PATCH_IF (~%war%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~war~) ~focus~
        END
        READ_2DA_ENTRY row 7 cols exp
        PATCH_IF (~%exp%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~pexp~) ~1~
        END
        PATCH_IF (~%exp%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mexp~) ~1~
        END
        PATCH_IF (~%exp%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~exp~) ~focus~
        END
        READ_2DA_ENTRY row 8 cols kno
        PATCH_IF (~%kno%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~pkno~) ~1~
        END
        PATCH_IF (~%kno%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mkno~) ~1~
        END
        PATCH_IF (~%kno%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~kno~) ~focus~
        END
        READ_2DA_ENTRY row 9 cols dec
        PATCH_IF (~%dec%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~pdec~) ~1~
        END
        PATCH_IF (~%dec%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mdec~) ~1~
        END
        PATCH_IF (~%dec%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~dec~) ~focus~
        END
        READ_2DA_ENTRY row 10 cols tho
        PATCH_IF (~%tho%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~ptho~) ~1~
        END
        PATCH_IF (~%tho%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mtho~) ~1~
        END
        PATCH_IF (~%tho%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~tho~) ~focus~
        END
        READ_2DA_ENTRY row 11 cols dre
        PATCH_IF (~%dre%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~pdre~) ~1~
        END
        PATCH_IF (~%dre%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mdre~) ~1~
        END
        PATCH_IF (~%dre%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~dre~) ~focus~
        END
        READ_2DA_ENTRY row 12 cols vig
        PATCH_IF (~%vig%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~pvig~) ~1~
        END
        PATCH_IF (~%vig%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mvig~) ~1~
        END
        PATCH_IF (~%vig%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~vig~) ~focus~
        END
        READ_2DA_ENTRY row 13 cols aff
        PATCH_IF (~%aff%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~paff~) ~1~
        END
        PATCH_IF (~%aff%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~maff~) ~1~
        END
        PATCH_IF (~%aff%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~aff~) ~focus~
        END
        READ_2DA_ENTRY row 14 cols ani
        PATCH_IF (~%ani%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~pani~) ~1~
        END
        PATCH_IF (~%ani%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mani~) ~1~
        END
        PATCH_IF (~%ani%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~ani~) ~focus~
        END
        READ_2DA_ENTRY row 15 cols pla
        PATCH_IF (~%pla%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~ppla~) ~1~
        END
        PATCH_IF (~%pla%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mpla~) ~1~
        END
        PATCH_IF (~%pla%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~pla~) ~focus~
        END
        READ_2DA_ENTRY row 16 cols ear
        PATCH_IF (~%ear%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~pear~) ~1~
        END
        PATCH_IF (~%ear%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mear~) ~1~
        END
        PATCH_IF (~%ear%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~ear~) ~focus~
        END
        READ_2DA_ENTRY row 17 cols wat
        PATCH_IF (~%wat%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~pwat~) ~1~
        END
        PATCH_IF (~%wat%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mwat~) ~1~
        END
        PATCH_IF (~%wat%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~wat~) ~focus~
        END
        READ_2DA_ENTRY row 18 cols air
        PATCH_IF (~%air%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~pair~) ~1~
        END
        PATCH_IF (~%air%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mair~) ~1~
        END
        PATCH_IF (~%air%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~air~) ~focus~
        END
        READ_2DA_ENTRY row 19 cols fir
        PATCH_IF (~%fir%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~pfir~) ~1~
        END
        PATCH_IF (~%fir%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mfir~) ~1~
        END
        PATCH_IF (~%fir%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~fir~) ~focus~
        END
        READ_2DA_ENTRY row 20 cols lig
        PATCH_IF (~%lig%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~plig~) ~1~
        END
        PATCH_IF (~%lig%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mlig~) ~1~
        END
        PATCH_IF (~%lig%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~lig~) ~focus~
        END
        READ_2DA_ENTRY row 21 cols sha
        PATCH_IF (~%sha%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~psha~) ~1~
        END
        PATCH_IF (~%sha%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~msha~) ~1~
        END
        PATCH_IF (~%sha%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~sha~) ~focus~
        END
        READ_2DA_ENTRY row 22 cols mag
        PATCH_IF (~%mag%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~pmag~) ~1~
        END
        PATCH_IF (~%mag%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mmag~) ~1~
        END
        PATCH_IF (~%mag%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~mag~) ~focus~
        END
        READ_2DA_ENTRY row 23 cols ast
        PATCH_IF (~%ast%~ STRING_EQUAL_CASE ~major~) BEGIN
    	  SPRINT $kit_spont_list(~past~) ~1~
        END
        PATCH_IF (~%ast%~ STRING_EQUAL_CASE ~minor~) BEGIN
    	  SPRINT $kit_spont_list(~mast~) ~1~
        END
        PATCH_IF (~%ast%~ STRING_EQUAL_CASE ~focus~) BEGIN
    	  SPRINT $kit_focus_list(~ast~) ~focus~
        END
      END
    END
  IF_EXISTS BUT_ONLY

/*
  ACTION_PHP_EACH kit_focus_list AS sph => ind BEGIN
	PRINT ~%sph%~
  END
  ACTION_PHP_EACH kit_spont_list AS sph_spls => ind BEGIN
	PRINT ~%sph_spls%~
  END
*/

// ***** real shamans need to add universal spells to this list
// ... or, just give them for free

  ACTION_PHP_EACH kit_spont_list AS sph_spls => ind BEGIN
	COPY_EXISTING ~%learn_res%.2da~ ~override~
	  LPM remove_blank_lines
	  APPEND_FILE ~override/d5t%sph_spls%.2da~
	BUT_ONLY
  END
  ACTION_IF (%kit_class% = 21) && (~%free_universal%~ STRING_EQUAL_CASE ~no~) BEGIN
	COPY_EXISTING ~%learn_res%.2da~ ~override~
	  LPM remove_blank_lines
	  APPEND_FILE ~override/d5tpuni.2da~
	BUT_ONLY
  END

  ACTION_IF (%kit_class% = 21) && (~%free_universal%~ STRING_EQUAL_CASE ~yes~) BEGIN
	COPY_EXISTING ~d5fnplst.2da~ ~override~
	  COUNT_2DA_COLS cols
	  COUNT_2DA_ROWS cols rows
	  FOR (row = 0; row < rows; ++row) BEGIN
		READ_2DA_ENTRY row 1 cols major
		READ_2DA_ENTRY row 4 cols sphe
		PATCH_IF (~%sphe%~ STRING_EQUAL_CASE ~universal~) BEGIN
		  INNER_ACTION BEGIN
			COPY_EXISTING ~d5tshun.spl~ ~override~
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%major%~ END
			IF_EXISTS BUT_ONLY
		  END
		END
	  END
	IF_EXISTS BUT_ONLY
	APPEND ~%kit_clab%.2da~ ~UNIVERSAL   AP_D5TSHUN  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
  END

  ACTION_IF (~%kit_clab%~ STRING_EQUAL_CASE ~clabsh01~) BEGIN
	COPY_EXISTING ~clabsh01.2da~ ~override~
	  COUNT_2DA_ROWS 10 rows
	  FOR (row = 0; row < rows; ++row) BEGIN
		READ_2DA_ENTRY row 1 10 shamspell
		PATCH_IF (~%shamspell%~ STRING_EQUAL_CASE ~GA_SPPR150~) BEGIN
		  REMOVE_2DA_ROW row 10
		END
	  END
	IF_EXISTS BUT_ONLY
  END

  OUTER_SPRINT seq_title @1000
  OUTER_SPRINT seq_label @1001
  
  ACTION_IF (%kit_class% = 6) || (%kit_class% = 12) BEGIN
	OUTER_SPRINT known_table ~d5_rpkn~
  END
  ELSE BEGIN
	OUTER_SPRINT known_table ~d5_shmkn~
  END

  ACTION_IF (VARIABLE_IS_SET %learn_res%) BEGIN
   LAF CREATE_SEQUENCER_MENU 
	INT_VAR 
	  name = RESOLVE_STR_REF (@1000)
	  tip = RESOLVE_STR_REF (@1000)
	  desc = RESOLVE_STR_REF (@1001)
	STR_VAR 
	  resref = EVAL ~%learn_res%~
	  spelltable = EVAL ~%known_table%~
	  spelllist = EVAL ~%learn_res%~
	  icon = ~spcl919b~
	  title = EVAL ~%seq_title%~
	  label = EVAL ~%seq_label%~
	  subspell = ~H~
   END
  END

  COPY_EXISTING ~%learn_res%.2da~ ~override/%learn_res%X.2da~
  IF_EXISTS

  COPY_EXISTING ~%learn_res%.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%learn_res%~ END
	LPF DELETE_EFFECT INT_VAR match_opcode = 172 STR_VAR match_resource = EVAL ~%learn_res%~ END
  IF_EXISTS

 END	//	end if kit is valid

END	//	end if sphere system

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5sham.2da~) BEGIN

 ACTION_FOR_EACH shortsphere IN ~uni~ ~lif~ ~dea~ ~ben~ ~des~ ~pro~ ~war~ ~exp~ ~kno~ ~dec~ ~tho~ ~dre~ ~vig~ ~aff~ ~ani~ ~pla~ ~ear~ ~air~ ~wat~ ~fir~ ~lig~ ~sha~ ~mag~ ~ast~ BEGIN
	ACTION_IF !(FILE_EXISTS_IN_GAME ~d5t0%shortsphere%.spl~) BEGIN
	  COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5t0%shortsphere%.spl~
	END
 END

 COPY_EXISTING ~d5fnplst.2da~ ~override~
	COUNT_2DA_COLS cols
	COUNT_2DA_ROWS cols rows
	FOR (row = 0; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY row 1 cols spel
	  READ_2DA_ENTRY row 5 cols spher
	  READ_2DA_ENTRY row 7 cols 206
	  SNPRINT 3 shrtsphr ~%spher%~
	  INNER_ACTION BEGIN
		COPY_EXISTING ~d5t0%shrtsphr%.spl~ ~override~
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%206%P~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%206%P~ END
		  PATCH_IF (~%shrtsphr%~ STRING_EQUAL_CASE ~uni~) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%spel%~ END
		  END
		IF_EXISTS BUT_ONLY
	  END
	END
 IF_EXISTS BUT_ONLY

<<<<<<<< d5/d5sham.2da
ABILITY     ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
>>>>>>>>
COPY ~d5/d5sham.2da~ ~override/d5sham.2da~

//add spell slot stat checks to SPLPROT_______________________________________________
//
APPEND ~splprot.2da~ ~D5_SHAM_1_7%TAB%134%TAB%-1%TAB%7~ UNLESS ~D5_SHAM_1_7~
APPEND ~splprot.2da~ ~D5_SHAM=1_7%TAB%134%TAB%-1%TAB%8~ UNLESS ~D5_SHAM=1_7~
APPEND ~splprot.2da~ ~D5_FATIGUE_IS%TAB%30%TAB%-1%TAB%1~ UNLESS ~D5_FATIGUE_IS~
APPEND ~splprot.2da~ ~D5_115_FEATS%TAB%115%TAB%-1%TAB%8~ UNLESS ~D5_115_FEATS~
APPEND ~splprot.2da~ ~D5_115_NFEATS%TAB%115%TAB%-1%TAB%9~ UNLESS ~D5_115_NFEATS~

COPY_EXISTING ~splprot.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_SHAM_1_7~ BEGIN
	  SET fake_sham_slots_1_7 = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_IS~ BEGIN
	  SET fatigue_value = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_115_FEATS~ BEGIN
	  SET 115_bit_row = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_115_NFEATS~ BEGIN
	  SET 115_not_row = %row%
	END
  END
BUT_ONLY

//create advance copies of some spells________________________________________________
//
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5sh206.spl~

COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5cspt0.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (115 + (0x10000 * 1)) timing = 9 END

COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot1a.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot1b.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot1c.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot1d.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot2a.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot2b.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot2c.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot2d.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot3a.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot3b.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot3c.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot3d.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot4a.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot4b.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot4c.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot4d.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot5a.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot5b.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot5c.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot5d.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot6a.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot6b.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot6c.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot6d.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot7a.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot7b.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot7c.spl~
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shot7d.spl~

COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shplz.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 4) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot1a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 4) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot1b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 4) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot1c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 4) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot1d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 8) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot2a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 8) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot2b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 8) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot2c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 8) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot2d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 12) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot3a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 12) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot3b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 12) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot3c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 12) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot3d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 16) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot4a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 16) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot4b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 16) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot4c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 16) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot4d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 20) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot5a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 20) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot5b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 20) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot5c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 20) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot5d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 24) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot6a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 24) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot6b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 24) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot6c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 24) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot6d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 28) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot7a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 28) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot7b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 28) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot7c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 28) parameter2 = %fake_sham_slots_1_7% timing = 1 STR_VAR resource = ~d5shot7d~ END

//assign stats for spell slots to each spell level____________________________________
//
// level 1 = (134 << 8)			// OR:	134 << 4
// level 2 = (134 << 12)		//		134 << 8
// level 3 = (134 << 16)		//		134 << 12
// level 4 = (134 << 20)		//		134 << 16
// level 5 = (108 << 8) 		//		134 << 20
// level 6 = (108 << 12)		//		134 << 24
// level 7 = (108 << 16)		//		134 << 28

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5shm1a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shm1%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 4) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5shm1%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5shm2a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shm2%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5shm2%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5shm3a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shm3%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5shm3%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5shm4a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shm4%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5shm4%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5shm5a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shm5%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5shm5%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5shm6a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shm6%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5shm6%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5shm7a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shm7%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 28) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5shm7%let%~ END
  END
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5shm-1.spl~ BEGIN
 COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shm-1.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 4) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5shm-2.spl~ BEGIN
 COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shm-2.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5shm-3.spl~ BEGIN
 COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shm-3.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5shm-4.spl~ BEGIN
 COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shm-4.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5shm-5.spl~ BEGIN
 COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shm-5.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5shm-6.spl~ BEGIN
 COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shm-6.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 24) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5shm-7.spl~ BEGIN
 COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shm-7.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 28) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END

//make necessary supporting files_____________________________________________________
//
/*
<<<<<<<< d5/d5fnp_spt_done.2da
SPELL
>>>>>>>>
COPY ~d5/d5fnp_spt_done.2da~ ~weidu_external/faiths_and_powers/d5fnp_spt_done.2da~
*/

ACTION_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~71~) OR (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~72~) BEGIN
<<<<<<<< d5/d5cwtch1.txt
BEGIN ~D5_CWTCH~

IF ~Global("D5_CWTCH","GLOBAL",1)~ THEN BEGIN d5_cwtch
SAY @141 
>>>>>>>> 
  COPY ~d5/d5cwtch1.txt~ ~weidu_external/faiths_and_powers/d5cwtch1.txt~

<<<<<<<< d5/d5cwtch2.txt
IF ~~ THEN REPLY @142 EXIT
END

>>>>>>>> 
  COPY ~d5/d5cwtch2.txt~ ~weidu_external/faiths_and_powers/d5cwtch2.txt~

  OUTER_SPRINT switch_prefix @141
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY majorminor BEGIN
	1 => P
//	2 => M
END

COPY_EXISTING ~d5fnplst.2da~ ~override~
  SET switch_ind = 1
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (row = 0; row < rows; ++row) BEGIN
	PHP_EACH majorminor AS col => suffix BEGIN
	  READ_2DA_ENTRY row 0 cols base_spl
	  READ_2DA_ENTRY row col cols fnp_spl
	  READ_2DA_ENTRY row 4 cols spher
	  READ_2DA_ENTRY row 6 cols spt_spl
	  READ_2DA_ENTRY row 7 cols 206_spl
	  READ_2DA_ENTRY row 8 cols lrn_spl
	  READ_2DA_ENTRY row 9 cols spt_eff
	  READ_2DA_ENTRY row 10 cols swch_spl
	  INNER_ACTION BEGIN
		ACTION_IF (FILE_EXISTS_IN_GAME ~%fnp_spl%.spl~) /*&& !(FILE_CONTAINS_EVALUATED (~weidu_external/faiths_and_powers/d5fnp_spt_done.2da~ ~%fnp_spl%[ %TAB%]~))*/ BEGIN
		  COPY_EXISTING ~%fnp_spl%.spl~ ~override~
			READ_LONG 0x34 spell_level
			READ_ASCII 0x3a spell_icon
			READ_STRREF NAME1 spell_name
		  BUT_ONLY
// make innates that cast the original
// ***** need to do differently if no sphere system...?
		  COPY_EXISTING ~%base_spl%.spl~ ~override/%spt_spl%%suffix%.spl~
			READ_SHORT 0x1c base_type
			WRITE_SHORT 0x1c 4
			WRITE_LONG 0x34 spell_level
			READ_LONG 0x64 abil_offset
			READ_SHORT 0x68 abil_number
			READ_BYTE (%abil_offset% + 0x0c) abil_target					
			READ_SHORT (%abil_offset% + 0x0e) abil_range
			READ_LONG 0x6a eff_offset
			WHILE (%abil_number% > 0) BEGIN
			  SET abil_number = (%abil_number% - 1)
			  WRITE_SHORT (%abil_offset% + 0x26 + (0x28 * %abil_number%)) 1
			END
			LPF DELETE_EFFECT END
			PATCH_IF (%abil_target% = 4) BEGIN
			  PATCH_IF base_type = 2 BEGIN
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = %spell_level% parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%base_spl%~ END
			  END
			  PATCH_IF base_type = 1 BEGIN
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = %spell_level% parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%fnp_spl%~ END
			  END
			  PATCH_IF (%abil_range% < 35) BEGIN
				PATCH_IF (%abil_range% > 4) BEGIN
					LPF ALTER_SPELL_HEADER INT_VAR range = (%abil_range% - 3) END
				END
				PATCH_IF (%abil_range% < 5) BEGIN
				  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END	
				END
			  END
			END
			ELSE BEGIN
			  PATCH_IF base_type = 2 BEGIN
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 power = %spell_level% parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~%base_spl%~ END
			  END
			  PATCH_IF base_type = 1 BEGIN
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 power = %spell_level% parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~%fnp_spl%~ END
			  END
			END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5shm-%spell_level%~ END
		  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5shplz~ END
		  IF_EXISTS
// make .EFFs adding the innate spell
		 ACTION_IF (spell_level < 8) BEGIN
		  CREATE EFF ~%spt_eff%%suffix%~
			WRITE_LONG 0x10 171
			WRITE_LONG 0x14 1
			WRITE_LONG 0x24 0
			WRITE_LONG 0x28 1
			WRITE_SHORT 0x2c 100
			WRITE_EVALUATED_ASCII 0x30 ~%spt_spl%%suffix%~ #8
			WRITE_LONG 0x90 1
			WRITE_EVALUATED_ASCII 0x94 ~%spt_eff%%suffix%~ #8
// make 206 spells preventing the .EFF
		  COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/%206_spl%%suffix%.spl~
			WRITE_SHORT 0x1c 4
		  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%spt_eff%%suffix%~ END
// add 206 spells to CLAB spell
		  COPY_EXISTING ~d5sh206.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~%206_spl%%suffix%~ END
// make learn spells canceling the 206
		  COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/%lrn_spl%%suffix%.spl~
			WRITE_EVALUATED_ASCII 0x3a ~%spell_icon%~ #8
		  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%206_spl%%suffix%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5sh206_spl~ END
//		  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = EVAL ~%fnp_spl%~ END
		  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5shplz~ END
//		  	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 parameter1 = 21 parameter2 = 105 target = 1 timing = 0 duration = 1 STR_VAR resource = EVAL ~%lrn_spl%%suffix%~ END
// make learn spell for UI learning system
		  COPY_EXISTING ~%fnp_spl%.spl~ ~override/%fnp_spl%H.spl~
			LPF ALTER_SPELL_HEADER INT_VAR projectile = 1 END
			LPF DELETE_EFFECT END
		  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%fnp_spl%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 timing = 1 STR_VAR resource = EVAL ~%lrn_spl%%suffix%~ END
		  	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 parameter1 = 21 parameter2 = 105 target = 1 timing = 0 duration = 1 STR_VAR resource = EVAL ~%lrn_spl%%suffix%~ END
// add 172 to d5shplz#
		  COPY_EXISTING ~d5shplz.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%spt_spl%%suffix%~ END
// generate slot#x spells
		  COPY_EXISTING ~d5shot%spell_level%a.spl~ ~override~
			LPF DELETE_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = EVAL ~%spt_eff%%suffix%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spt_eff%%suffix%~ END
		  COPY_EXISTING ~d5shot%spell_level%b.spl~ ~override~
			LPF DELETE_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = EVAL ~%spt_eff%%suffix%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spt_eff%%suffix%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spt_eff%%suffix%~ END
		  COPY_EXISTING ~d5shot%spell_level%c.spl~ ~override~
			LPF DELETE_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = EVAL ~%spt_eff%%suffix%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spt_eff%%suffix%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spt_eff%%suffix%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spt_eff%%suffix%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spt_eff%%suffix%~ END
		  COPY_EXISTING ~d5shot%spell_level%d.spl~ ~override~
			LPF DELETE_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = EVAL ~%spt_eff%%suffix%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spt_eff%%suffix%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spt_eff%%suffix%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spt_eff%%suffix%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spt_eff%%suffix%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spt_eff%%suffix%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spt_eff%%suffix%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spt_eff%%suffix%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spt_eff%%suffix%~ END
		  ACTION_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~71~) OR (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~72~) BEGIN
			ACTION_IF !(~%spher%~ STRING_EQUAL_CASE ~Universal~) BEGIN
			  COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/%swch_spl%.spl~
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = EVAL ~%fnp_spl%~ END
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = EVAL ~%lrn_spl%%suffix%~ END 
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%206_spl%%suffix%~ END
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5shplz~ END
		      OUTER_SPRINT switch_spell_text ~%switch_prefix%: %spell_name%~
			  APPEND_OUTER ~weidu_external/faiths_and_powers/d5cwtch1.txt~ ~~~~~IF ~HaveKnownSpellRES("%fnp_spl%")~ THEN REPLY ~%spell_name%~ GOTO d5_cwtch_%switch_ind%~~~~~ KEEP_CRLF
			  APPEND_OUTER ~weidu_external/faiths_and_powers/d5cwtch2.txt~ ~~~~~IF ~~ THEN BEGIN d5_cwtch_%switch_ind% %WNL% SAY ~%switch_spell_text%~ %WNL% IF ~~ THEN REPLY @143 DO ~ApplySpellRES("%swch_spl%",myself)~ EXIT %WNL% IF ~~ THEN REPLY @144 GOTO d5_cwtch %WNL% IF ~~ THEN REPLY @142 EXIT %WNL% END %WNL%~~~~~ KEEP_CRLF
			END
		  END
		 END
//		APPEND_OUTER ~weidu_external/faiths_and_powers/d5fnp_spt_done.2da~ ~%fnp_spl%	done~
		END
	  END
	  SET ++switch_ind
	END
  END
BUT_ONLY


//spell switching finish_______________________________________________________________
//
ACTION_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~71~) OR (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~72~) BEGIN

 COPY ~weidu_external/faiths_and_powers/d5cwtch1.txt~ ~weidu_external/faiths_and_powers/d5cwtch.d~
  APPEND_FILE ~weidu_external/faiths_and_powers/d5cwtch2.txt~

COMPILE ~weidu_external/faiths_and_powers/d5cwtch.d~

<<<<<<<< d5/d5cwtch.baf
IF
	Global("D5_CWTCH","GLOBAL",0)
THEN
	RESPONSE #100
	SetGlobal("D5_CWTCH","GLOBAL",1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("d5_cwtch",Myself))
END
IF
	Global("D5_CWTCH","GLOBAL",1)
THEN
	RESPONSE #100
	SetGlobal("D5_CWTCH","GLOBAL",0)
	DestroySelf()
END
>>>>>>>> 
COPY ~d5/d5cwtch.baf~ ~weidu_external/faiths_and_powers/d5cwtch.baf~

COMPILE ~weidu_external/faiths_and_powers/d5cwtch.baf~

COPY ~%MOD_FOLDER%/data/semi_spont/d5swtch.bam~ ~override~

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5cwtch.spl~
  SAY NAME1 @141
  SAY UNIDENTIFIED_DESC @141
  WRITE_SHORT 0x1c 4
  WRITE_ASCII 0x3a ~d5swtch~ #8
  LPF ALTER_SPELL_HEADER INT_VAR location = 4 target = 5 STR_VAR icon = ~d5swtch~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 0 duration = 12 STR_VAR resource = ~d5cwtch~ END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 99 opcode = 172 target = 1 STR_VAR resource = ~d5cwtch~ END

CREATE EFF ~d5cwtch~
	WRITE_LONG 0x10 67
	WRITE_LONG 0x14 1
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 0
	WRITE_LONG 0x28 12
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~d5cwtch~ #8
	WRITE_ASCII 0x70 ~d5_null~ #8

COPY ~faiths_and_powers/kits/misc/d5cwtch.cre~ ~override~

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5cwch2.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = (1 << 24) parameter2 = %115_bit_row% timing = 1 STR_VAR resource = ~d5cwch1~ END

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5cwch1.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 318 target = 1 parameter1 = (1 << 24) parameter2 = %115_bit_row% timing = 0 duration = 1 STR_VAR resource = ~d5cwch1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5cwtch~ END

END	//	end if switching

//apply EFF protections_______________________________________________________________
//
APPEND ~d5sham.2da~ ~NO_SPLS     AP_D5CSPT0 ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

COPY_EXISTING ~d5fpspt.spl~ ~override~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (115 + (0x10000 * 1)) timing = 9 END
  PATCH_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SPONT_DIVINE~)) BEGIN
	INNER_ACTION BEGIN
	  COPY_EXISTING ~splstate.ids~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
		  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
		  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_SPONT_DIVINE~) BEGIN
			SET spont_divine_state = %state_ind%
		  END
		END
	  BUT_ONLY
	END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 328 target = 1 special = 1 parameter2 = %spont_divine_state% timing = 9 END
  END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5cspt0~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5sh206~ END
IF_EXISTS BUT_ONLY

/*
ACTION_IF FILE_EXISTS_IN_GAME ~d5t0uni.spl~ BEGIN
  ACTION_PHP_EACH fnp_spont_unispls AS fnp_spl => spt_spl BEGIN
	OUTER_TEXT_SPRINT 206_spl ~%fnp_spl_1%~
	OUTER_TEXT_SPRINT lrn_spl ~%fnp_spl_2%~
	OUTER_TEXT_SPRINT spt_eff ~%fnp_spl_3%~
	COPY_EXISTING ~d5t0uni.spl~ ~override~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%206_spl%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%206_spl%~ END
	IF_EXISTS BUT_ONLY
  END
END
*/

//remove all cleric spell slots_______________________________________________________
//
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d50cslt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
BUT_ONLY

APPEND ~d5sham.2da~ ~NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
~

COPY_EXISTING ~d5fpspt.spl~ ~override~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
IF_EXISTS BUT_ONLY

//daily spell slot refresh____________________________________________________________
//
COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shotz.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~d5shots~ END

//APPEND ~d5sham.2da~ ~UNLESS ~SPLSLOTS~    AP_D5SHOTZ  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

CREATE EFF ~d5shots~
  WRITE_LONG 0x10 232
  WRITE_LONG 0x14 1
  WRITE_LONG 0x1c 0
  WRITE_LONG 0x20 20
  WRITE_LONG 0x24 9
  WRITE_SHORT 0x2c 100
  WRITE_ASCII 0x30 ~d5shlot~ #8
  WRITE_LONG 0x48 102

COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shlot.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %fatigue_value% timing = 1 STR_VAR resource = ~d5shfrsh~ END


// spell to refresh spell slots_______________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5shfrsh.spl~ BEGIN
 COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shfrsh.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 1 timing = 1 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-2~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-3~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-4~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-5~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-6~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-7~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5shplz~ END
END

// remove spells if no spheres________________________________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5_spheres.d5~) BEGIN

//***** this needs to be rewritten
// make a version for just universal spells (see multidruids):
// ... only for sphere system and free_universal = no
// ... don't include in d5sham.2da; conditionally apply to each kit 
// make a version for all divine spells:
// ... only for no spheres 
// ... apply to d5sham.2da

 COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5xpall.spl~

 COPY_EXISTING_REGEXP GLOB ~^SPPR[1-7]\(0[1-9]\|[1-4][0-9]\|50\)\.spl$~ ~override~
  READ_BYTE 0x21 exclusion
  PATCH_IF (%exclusion% BOR 0b01111111 = 0b01111111) || (%exclusion% BOR 0b10111111 = 0b10111111) BEGIN
	LPF NAME_NUM_OF_SPELL_RES STR_VAR spell_res = EVAL ~%SOURCE_RES%~ RET spell_name END
	PATCH_IF (FILE_CONTAINS_EVALUATED (~spell.ids~ ~%spell_name%[ %TAB%%LNL%%MNL%%WNL%]~)) && !(FILE_CONTAINS_EVALUATED (~hidespl.2da~ ~%SOURCE_RES%~)) BEGIN
	  TEXT_SPRINT the_spell ~%SOURCE_RES%~
	  INNER_PATCH_SAVE removal_eff ~%the_spell%~ BEGIN
		REPLACE_TEXTUALLY ~^[Ss][Pp][Pp][Rr]~ ~D5XP~
	  END
	  INNER_ACTION BEGIN
		CREATE EFF ~%removal_eff%~
		  WRITE_LONG 0x10 172
		  WRITE_LONG 0x14 1
		  WRITE_LONG 0x24 9
		  WRITE_SHORT 0x2c 100
		  WRITE_EVALUATED_ASCII 0x30 ~%the_spell%~ #8
		  WRITE_LONG 0x90 1
		  WRITE_EVALUATED_ASCII 0x94 ~%removal_eff%~ #8
		COPY_EXISTING ~d5xpall.spl~ ~override~
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 4 duration = 1 STR_VAR resource = EVAL ~%removal_eff%~ END
		BUT_ONLY
		COPY_EXISTING ~d5shclon.2da~ ~override~
		  COUNT_2DA_COLS cols
		  READ_2DA_ENTRIES_NOW ~r2en_shclon~ cols
		  FOR (ind = 0; ind < r2en_shclon; ++ind) BEGIN
			READ_2DA_ENTRY_FORMER ~r2en_shclon~ ind 0 book_spl_res
			READ_2DA_ENTRY_FORMER ~r2en_shclon~ ind 2 learn_spl_res
			PATCH_IF (~%book_spl_res%~ STRING_EQUAL_CASE ~%the_spell%~) BEGIN
			  INNER_PATCH_SAVE removal_eff ~%book_spl_res%~ BEGIN
				REPLACE_TEXTUALLY ~^[Ss][Pp][Pp][Rr]~ ~D5XP~
			  END
			  TEXT_SPRINT $all_spontaneous(~%book_spl_res%~ ~%learn_spl_res%~) ~%removal_eff%~
			END
		  END
		BUT_ONLY
	  END
	END
  END
 BUT_ONLY

 ACTION_PHP_EACH all_spontaneous AS allspl => remeff BEGIN
  OUTER_SPRINT lrnspl ~%allspl_1%~
  ACTION_IF (FILE_EXISTS_IN_GAME ~%lrnspl%.spl~) BEGIN
	COPY_EXISTING ~%lrnspl%.spl~ ~override~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%remeff%~ END
	BUT_ONLY
  END
 END

 APPEND ~d5sham.2da~ ~NO_SPELLS   AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL ~

/* 
// for spell-based spontaneous, apply this^^ to every cleric kit
// ... starting at 2nd level
// ... apply a 206 spell at 1st level (hopefully that works with high-level starts)
// ... remove the 206 spell and apply d5xpall upon choosing to go spontaneous

 COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5xp206.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5xpall~ END

 ACTION_IF (%kit_class% != 21) BEGIN
  APPEND ~%kit_clab%.2da~ ~NO_SPELLS   AP_D5XP206  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL  AP_D5XPALL ~

 COPY_EXISTING ~d5fpspt.spl~ ~override~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5xp206~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5xpall~ END
 IF_EXISTS BUT_ONLY
*/

END

//disable quickspell buttons and scroll learning______________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5srcnq.spl~) BEGIN
  COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5srcnq.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 3 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 4 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 5 timing = 9 END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 101 target = 1 parameter2 = 147 timing = 9 END
END

APPEND ~d5sham.2da~ ~NO_QUICK    AP_D5SRCNQ  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

COPY_EXISTING ~d5fpspt.spl~ ~override~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 3 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 4 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 5 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 101 target = 1 parameter2 = 147 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 24) parameter2 = %115_not_row% timing = 9 STR_VAR resource = ~d5shmsp~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 24) parameter2 = %115_bit_row% timing = 9 STR_VAR resource = ~d5shmsw~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 24) parameter2 = %kit_is_row% timing = 9 STR_VAR resource = ~d5shami~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5msorc~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = ~d5spm3m~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = ~d5fpspt~ END
IF_EXISTS BUT_ONLY

COPY_EXISTING ~d5fnplst.2da~ ~override~
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (row = 0; row < rows; ++row) BEGIN
	READ_2DA_ENTRY row 1 cols major
	READ_2DA_ENTRY row 2 cols minor
	READ_2DA_ENTRY row 3 cols focus
	READ_2DA_ENTRY row 4 cols sphe
	PATCH_IF !(~%sphe%~ STRING_EQUAL_CASE ~universal~) BEGIN
	  PATCH_IF !(~%major%~ STRING_EQUAL_CASE ~****~) BEGIN
		TEXT_SPRINT $divine_spont_remove_spells(~%major%~) ~1~
	  END
	  PATCH_IF !(~%minor%~ STRING_EQUAL_CASE ~****~) BEGIN
		TEXT_SPRINT $divine_spont_remove_spells(~%minor%~) ~1~
	  END
	  PATCH_IF !(~%focus%~ STRING_EQUAL_CASE ~****~) BEGIN
		TEXT_SPRINT $divine_spont_remove_spells(~%focus%~) ~1~
	  END
	END
  END
IF_EXISTS BUT_ONLY
  
COPY_EXISTING ~d5fpspt.spl~ ~override~
  PHP_EACH divine_spont_remove_spells AS rem_spl => ind BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = EVAL ~%rem_spl%~ END
  END
IF_EXISTS BUT_ONLY

// bonus spell slot items_____________________________________________________________
//
LAF divine_spont_items END

// bonus WIS casting slots____________________________________________________________
//
ACTION_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~95~) BEGIN
  LAM semi_wis_slots
END


END	//	end if d5sham.2da doesn't exist -- above code only needs to be run once

COPY_EXISTING ~splprot.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_SHAM_1_7~ BEGIN
	  SET fake_sham_slots_1_7 = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_IS~ BEGIN
	  SET fatigue_value = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_115_FEATS~ BEGIN
	  SET 115_bit_row = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_115_NFEATS~ BEGIN
	  SET 115_not_row = %row%
	END
  END
BUT_ONLY

ACTION_IF (%kit_class% = 6) || (%kit_class% = 12) BEGIN
  APPEND ~%kit_clab%.2da~ ~SPLSLOTS    ****        ****        AP_D5SHM1A  AP_D5SHM1B  AP_D5SHM1C  AP_D5SHM1D  AP_D5SHM2A  AP_D5SHM2B  AP_D5SHM2C  AP_D5SHM1E  AP_D5SHM3A  AP_D5SHM3B  AP_D5SHM3C  AP_D5SHM2D  AP_D5SHM4A  AP_D5SHM4B  AP_D5SHM4C  AP_D5SHM2E  AP_D5SHM1F  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
SPLSLOTS    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        AP_D5SHM3D  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
~ UNLESS ~SPLSLOTS~
END
ACTION_IF (%kit_class% != 6) && (%kit_class% != 12) && (%kit_class% != 21) BEGIN
  APPEND ~%kit_clab%.2da~ ~SPLSLOTS    AP_D5SHM1A  AP_D5SHM1D  AP_D5SHM1E  AP_D5SHM1F  AP_D5SHM2D  AP_D5SHM2E  AP_D5SHM2F  AP_D5SHM3E  AP_D5SHM3F  AP_D5SHM4E  AP_D5SHM4F  AP_D5SHM5E  AP_D5SHM5F  AP_D5SHM6E  AP_D5SHM6F  AP_D5SHM7E  AP_D5SHM7F  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
SPLSLOTS    AP_D5SHM1B  AP_D5SHM1A  ****        AP_D5SHM2A  ****        AP_D5SHM3A  AP_D5SHM3D  AP_D5SHM4A  AP_D5SHM4D  AP_D5SHM5A  AP_D5SHM5D  AP_D5SHM6A  AP_D5SHM6D  AP_D5SHM7A  AP_D5SHM7D  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
SPLSLOTS    AP_D5SHM1C  AP_D5SHM1B  ****        AP_D5SHM2B  ****        AP_D5SHM3B  ****        AP_D5SHM4B  ****        AP_D5SHM5B  ****        AP_D5SHM6B  ****        AP_D5SHM7B  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
SPLSLOTS    ****        AP_D5SHM1C  ****        AP_D5SHM2C  ****        AP_D5SHM3C  ****        AP_D5SHM4C  ****        AP_D5SHM5C  ****        AP_D5SHM6C  ****        AP_D5SHM7C  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
~ UNLESS ~SPLSLOTS~
END

ACTION_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~72~) BEGIN
  APPEND ~%kit_clab%.2da~ ~SWITCH_SPL  AP_D5CSPT0  ****        AP_D5CWCH1  ****        ****        AP_D5CWCH1  ****        ****        AP_D5CWCH1  ****        ****        AP_D5CWCH1  ****        ****        AP_D5CWCH1  ****        ****       AP_D5CWCH1  ****        ****        AP_D5CWCH1  ****        ****        AP_D5CWCH1  ****        ****        AP_D5CWCH1  ****        ****        AP_D5CWCH1  ****        ****        AP_D5CWCH1  ****        ****        AP_D5CWCH1  ****        ****        AP_D5CWCH1  ****        ****        AP_D5CWCH1  ****        ****        AP_D5CWCH1  ****        ****        AP_D5CWCH1  ****        **** ~ UNLESS ~SWITCH_SPL~
END
ACTION_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~71~) BEGIN
  APPEND ~%kit_clab%.2da~ ~SWITCH_SPL  AP_D5CSPT0  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1 AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1  AP_D5CWCH1 ~ UNLESS ~SWITCH_SPL~
END

//initial memorizer = shamans only____________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5_spheres.d5~) BEGIN
  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5spmxm.spl~) BEGIN
	COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5spmxm.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5spmem~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 4 duration = 1 STR_VAR resource = ~d5spm3m~ END
  END
  ACTION_IF !(%kit_class% = 21) && (d5_spell_spontaneous = 0) BEGIN
	APPEND ~%kit_clab%.2da~ ~NO_SLEEP     AP_D5SPMXM  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
  END
END
ACTION_IF (%kit_class% = 21) BEGIN
  APPEND ~%kit_clab%.2da~ ~SPL_REST     GA_D5SPM3M  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ UNLESS ~SPL_REST~
END

COPY ~faiths_and_powers/kits/misc/d5lernpr.bam~ ~override~
COPY ~faiths_and_powers/kits/misc/d5lernwi.bam~ ~override~

ACTION_IF (FILE_EXISTS_IN_GAME ~d5shmsp.itm~) BEGIN
 COPY_EXISTING ~d5shmsp.itm~ ~override~
  LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 326 parameter1 = %kit_ids% parameter2 = %kit_is_row% STR_VAR resource = EVAL ~%learn_res%~ END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shmsp.itm~) BEGIN
 COPY ~faiths_and_powers/kits/multiclass/499_shambarb/d5shmsp.itm~ ~override~
  SAY NAME1 @49911
  SAY NAME2 @49911
  SAY UNIDENTIFIED_DESC @49912
  SAY IDENTIFIED_DESC @49912
  LPF ALTER_ITEM_HEADER INT_VAR header = 1 target = 7 speed = 0 STR_VAR icon = ~d5lernpr~ END
  LPF ALTER_EFFECT INT_VAR match_opcode = 146 opcode = 326 parameter1 = %kit_ids% parameter2 = %kit_is_row% STR_VAR resource = EVAL ~%learn_res%~ END
END

OUTER_INNER_PATCH ~1~ BEGIN
  WRITE_BYTE 0 0x09
  READ_ASCII 0 tab (1)  // 0x09, tab
  WRITE_BYTE 0 0x0d
  READ_ASCII 0 mnl (1)  // 0x0d, Mac
END
LAF ~ADD_ITEM_TOOLTIPS~ STR_VAR item = ~d5shmsw~ tooltips = ~@49911~ END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5shmsw.itm~) BEGIN
 COPY_EXISTING ~d5shmsw.itm~ ~override~
  LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 326 parameter1 = %kit_ids% parameter2 = %kit_is_row% STR_VAR resource = EVAL ~%learn_res%~ END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shmsw.itm~) BEGIN
 COPY ~faiths_and_powers/kits/multiclass/499_shambarb/d5shmsw.itm~ ~override~
  SAY NAME1 @49915
  SAY NAME2 @49915
  SAY UNIDENTIFIED_DESC @49916
  SAY IDENTIFIED_DESC @49916
  LPF ALTER_ITEM_HEADER INT_VAR header = 1 target = 7 speed = 0 STR_VAR icon = ~d5lernwi~ END
  LPF ALTER_ITEM_HEADER INT_VAR header = 2 target = 7 speed = 0 STR_VAR icon = ~d5lernpr~ END
  LPF ALTER_EFFECT INT_VAR match_opcode = 146 opcode = 326 parameter1 = %kit_ids% parameter2 = %kit_is_row% STR_VAR match_resource = ~d5msham~ resource = EVAL ~%learn_res%~ END
END

OUTER_INNER_PATCH ~1~ BEGIN
  WRITE_BYTE 0 0x09
  READ_ASCII 0 tab (1)  // 0x09, tab
  WRITE_BYTE 0 0x0d
  READ_ASCII 0 mnl (1)  // 0x0d, Mac
END
LAF ~ADD_ITEM_TOOLTIPS~ STR_VAR item = ~d5shmsw~ tooltips = ~@49913 @49911~ END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5shnit.spl~) BEGIN
  COPY_EXISTING ~d5shnit.spl~ ~override~
	SAY NAME1 @49950
	SAY UNIDENTIFIED_DESC @49950
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %kit_ids% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = EVAL ~%learn_res%b~ END
	PATCH_IF (FILE_EXISTS_IN_GAME ~d5t0uni.spl~) && !(~%free_universal%~ STRING_EQUAL_CASE ~no~) BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %kit_ids% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = ~d5t0uni~ END
	END
	PHP_EACH kit_focus_list AS sphr => foc BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5t0%sphr%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %kit_ids% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = EVAL ~d5t0%sphr%~ END
	  END
	END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shnit.spl~) BEGIN
  COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shnit.spl~				//	initialize shaman casting
	SAY NAME1 @49950
	SAY UNIDENTIFIED_DESC @49950
	WRITE_SHORT 0x1c 4
	LPF ALTER_SPELL_HEADER INT_VAR location = 4 target = 5 STR_VAR icon = ~d5lernpr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5msorc~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 24) parameter2 = %115_not_row% timing = 9 STR_VAR resource = ~d5shmsp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 24) parameter2 = %115_bit_row% timing = 9 STR_VAR resource = ~d5shmsw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %kit_ids% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = EVAL ~%learn_res%b~ END
	PATCH_IF (FILE_EXISTS_IN_GAME ~d5t0uni.spl~) && !(~%free_universal%~ STRING_EQUAL_CASE ~no~) BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %kit_ids% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = ~d5t0uni~ END
	END
	PHP_EACH kit_focus_list AS sphr => foc BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5t0%sphr%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %kit_ids% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = EVAL ~d5t0%sphr%~ END
	  END
	END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5shnit~ END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~%learn_res%b.spl~) BEGIN
  COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/%learn_res%b.spl~			//	initialize shaman abilities
	PATCH_IF (%kit_class% != 21) && !(~%kit_clab%~ STRING_EQUAL_CASE ~clabsh01~) && !(~%kit_clab%~ STRING_EQUAL_CASE ~clabshgs~) BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 1 STR_VAR resource = ~d5shots~ END
	END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5shfre~ END // apply in sham clabs, only if no spheres (?)
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shmsp.spl~) BEGIN
  COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shmsp.spl~			//	add learn spells item
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5shmsp~ END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shmsw.spl~) BEGIN
  COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shmsw.spl~			//	add learn spells item
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5shmsw~ END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shamb.spl~) BEGIN
  COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shami.spl~			//	add learn spells item
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5shamb~ END
END

COPY_EXISTING ~d5fpspt.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %kit_ids% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = EVAL ~%learn_res%b~ END
	PATCH_IF (FILE_EXISTS_IN_GAME ~d5t0uni.spl~) && !(~%free_universal%~ STRING_EQUAL_CASE ~no~) BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %kit_ids% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = ~d5t0uni~ END
	END
	PHP_EACH kit_focus_list AS sphr => foc BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5t0%sphr%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %kit_ids% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = EVAL ~d5t0%sphr%~ END
	  END
	END
	PATCH_IF (~%kit_clab%~ STRING_EQUAL_CASE ~d5shmbb~) || (~%kit_clab%~ STRING_EQUAL_CASE ~d5shmrn~) || (~%kit_clab%~ STRING_EQUAL_CASE ~d5shmth~) || (~%kit_clab%~ STRING_EQUAL_CASE ~d5shmma~) || (~%kit_clab%~ STRING_EQUAL_CASE ~d5shmnk~) BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %kit_ids% parameter2 = %kit_is_row% timing = 4 duration = 1 STR_VAR resource = ~d5shami~ END
	END
IF_EXISTS BUT_ONLY

ACTION_IF /*(%kit_class% != 6) && (%kit_class% != 12) &&*/ (%kit_class% != 21) BEGIN
 ACTION_IF (d5_spell_spontaneous = 0) || (~%kit_clab%~ STRING_EQUAL_CASE ~d5shmbb~) || (~%kit_clab%~ STRING_EQUAL_CASE ~d5shmrn~) || (~%kit_clab%~ STRING_EQUAL_CASE ~d5shmth~) || (~%kit_clab%~ STRING_EQUAL_CASE ~d5shmma~) || (~%kit_clab%~ STRING_EQUAL_CASE ~d5shmnk~) BEGIN
  COPY_EXISTING ~%kit_clab%.2da~ ~override~
	APPEND_FILE ~override/d5sham.2da~
  IF_EXISTS
 END
 ACTION_IF (d5_spell_spontaneous > 0) BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%kit_clab%.2da~) BEGIN
	ACTION_IF !(~%kit_clab%~ STRING_EQUAL_CASE ~d5shmbb~) && !(~%kit_clab%~ STRING_EQUAL_CASE ~d5shmrn~) && !(~%kit_clab%~ STRING_EQUAL_CASE ~d5shmth~) && !(~%kit_clab%~ STRING_EQUAL_CASE ~d5shmma~) && !(~%kit_clab%~ STRING_EQUAL_CASE ~d5shmnk~) BEGIN
	  APPEND ~%kit_clab%.2da~ ~SPNT_SPLS    GA_D5FPSP2  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
	END
	ACTION_IF (~%kit_clab%~ STRING_EQUAL_CASE ~d5shmbb~) || (~%kit_clab%~ STRING_EQUAL_CASE ~d5shmrn~) || (~%kit_clab%~ STRING_EQUAL_CASE ~d5shmth~) || (~%kit_clab%~ STRING_EQUAL_CASE ~d5shmma~) || (~%kit_clab%~ STRING_EQUAL_CASE ~d5shmnk~) BEGIN
	  APPEND ~%kit_clab%.2da~ ~SPNT_SPLS    GA_D5FPSPT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
	  APPEND ~%kit_clab%.2da~ ~SPNT_SPLS    AP_D5FPSP3  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
	END
  END
 END
END

COPY ~faiths_and_powers/kits/misc/d5_base.spl~ ~override/d5shni2.spl~
  SAY NAME1 @49950
  SAY UNIDENTIFIED_DESC @49950
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5shnit~ END

ACTION_IF (d5_spell_spontaneous = 0) BEGIN
  APPEND ~%kit_clab%.2da~ ~LEARNSPLS   GA_D5SHNIT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
  APPEND ~%kit_clab%.2da~ ~LEARNSPLS   AP_D5SHNI2  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
END


//fix burning hands targeting_______________________________________________________
//
COPY_EXISTING ~spwi103.spl~ ~override~
  READ_LONG 0x08 burning_hands_strref
BUT_ONLY

ACTION_IF (IS_AN_INT %burning_hands_strref%) BEGIN
  COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
	PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
	  SET burning_change = 0
	  READ_LONG 0x08 name
	  PATCH_IF (name = burning_hands_strref) BEGIN
		GET_OFFSET_ARRAY ab_array SPL_V10_HEADERS
		PHP_EACH ab_array AS int => ab_off BEGIN
		  PATCH_IF (burning_change = 0) BEGIN
			READ_BYTE (ab_off + 0x0c) target
			PATCH_IF target = 5 BEGIN
			  SET burning_change = 1
			END
		  END
		END
		PATCH_IF (burning_change = 1) BEGIN
		  LPF ALTER_SPELL_HEADER INT_VAR target = 1 END
		  LPF ALTER_EFFECT INT_VAR match_opcode = 148 opcode = 146 target = 2 STR_VAR match_resource = ~spwi103~ END
		  LPF ALTER_EFFECT INT_VAR match_opcode = 148 opcode = 146 target = 2 STR_VAR match_resource = ~d5p2103~ END
		END
	  END
	END
  BUT_ONLY
END
//__________________________________________________________________________________


/*

//MAKE +SPELL SLOT ITEMS WORK________________________________________________________
//
// make EFFs to increase spontaneous casting slots
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5shc1e.eff~ BEGIN
  CREATE EFF ~d5shc1e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 4)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SHC1E~ #8
  CREATE EFF ~d5shc2e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 8)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SHC2E~ #8
  CREATE EFF ~d5shc3e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 12)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SHC3E~ #8
  CREATE EFF ~d5shc4e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 16)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SHC4E~ #8
  CREATE EFF ~d5shc5e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 20)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SHC5E~ #8
  CREATE EFF ~d5shc6e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 24)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SHC6E~ #8
  CREATE EFF ~d5shc7e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 28)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SHC7E~ #8
  CREATE EFF ~d5shc1f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 4)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SHC1F~ #8
  CREATE EFF ~d5shc2f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 8)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SHC2F~ #8
  CREATE EFF ~d5shc3f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 12)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SHC3F~ #8
  CREATE EFF ~d5shc4f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 16)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SHC4F~ #8
  CREATE EFF ~d5shc5f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 20)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SHC5F~ #8
  CREATE EFF ~d5shc6f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 24)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SHC6F~ #8
  CREATE EFF ~d5shc7f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 28)
	WRITE_LONG 0x20 (134 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SHC7F~ #8
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d51l1dsp.eff~ BEGIN
// make EFFs to increase traditional mem/cast slots by 1
  CREATE EFF ~d51l1dsp~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 1
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L1DSP~ #8
  CREATE EFF ~d51l2DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 2
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L2DSP~ #8
  CREATE EFF ~d51l3DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 4
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L3DSP~ #8
  CREATE EFF ~d51l4DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 8
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L4DSP~ #8
  CREATE EFF ~d51l5DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 16
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L5DSP~ #8
  CREATE EFF ~d51l6DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 32
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L6DSP~ #8
  CREATE EFF ~d51l7DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 64
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L7DSP~ #8

// make EFFs to increase traditional mem/cast slots by 2
  CREATE EFF ~D52L1DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 1
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L1DSP~ #8
  CREATE EFF ~D52L2DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 2
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L2DSP~ #8
  CREATE EFF ~D52L3DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 4
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L3DSP~ #8
  CREATE EFF ~D52L4DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 8
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L4DSP~ #8
  CREATE EFF ~D52L5DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 16
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L5DSP~ #8
  CREATE EFF ~D52L6DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 32
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L6DSP~ #8
  CREATE EFF ~D52L7DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 64
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L7DSP~ #8

// make EFFs to double traditional mem/cast slots
  CREATE EFF ~D5XL1DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL1DSP~ #8
  CREATE EFF ~D5XL2DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 2
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL2DSP~ #8
  CREATE EFF ~D5XL3DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 3
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL3DSP~ #8
  CREATE EFF ~D5XL4DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 4
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL4DSP~ #8
  CREATE EFF ~D5XL5DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 5
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL5DSP~ #8
  CREATE EFF ~D5XL6DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 6
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL6DSP~ #8
  CREATE EFF ~D5XL7DSP~
	WRITE_LONG 0x10 62
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 7
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL7DSP~ #8

 OUTER_SET spellslot_item_ind = 0
 OUTER_SPRINT $spell_slot_items(~%spellslot_item_ind%~) ~spell_slot_item~
 COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
  	SET plus_slots = 0
	READ_BYTE     0x2f current ELSE 0
	READ_BYTE     0x2b current2 ELSE 0
	READ_LONG 0x64 headoffset  ELSE 0
	READ_SHORT 0x68 headcount  ELSE 0
	READ_LONG 0x6a effectsoffset  ELSE 0
	FOR (headcyc = 0; headcyc < headcount ; headcyc = headcyc + 1) BEGIN
      this_head = 0
	  READ_SHORT (headoffset + (headcyc * 0x38) + 0x1e) effcount  ELSE 0
	  READ_SHORT (headoffset + (headcyc * 0x38) + 0x20) effectsindex  ELSE 0
	  FOR (effcyc = 0; effcyc < effcount; effcyc = effcyc + 1) BEGIN
		READ_SHORT (effectsoffset + (effectsindex + effcyc)* 0x30) opcode ELSE 0
		PATCH_IF (opcode = 62) AND (this_head = 0) BEGIN
		  SET plus_slots = 1
		  SET this_head = 1
		END
	  END
	END
	PATCH_IF (plus_slots = 1)BEGIN
	  SPRINT $spell_slot_items(~%spellslot_item_ind%~) ~%SOURCE_RES%~
	  SET ++spellslot_item_ind
	END
  END
 BUT_ONLY
	  
 ACTION_PHP_EACH spell_slot_items AS ind => slot_item BEGIN
  COPY_EXISTING ~%slot_item%.itm~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 1   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc1e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 2   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc2e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 4   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc3e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 8   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc4e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 16  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc5e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 32  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc6e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 64  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc7e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 128 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc8e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 256 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc9e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 1   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc1f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 2   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc2f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 4   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc3f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 8   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc4f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 16  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc5f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 32  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc6f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 64  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc7f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 128 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc8f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 256 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5shc9f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 1   opcode = 177 parameter1 = 1 parameter2 = 0 timing = 2 STR_VAR resource = ~d5shc1f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 2   opcode = 177 parameter1 = 2 parameter2 = 0 timing = 2 STR_VAR resource = ~d5shc2f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 4   opcode = 177 parameter1 = 3 parameter2 = 0 timing = 2 STR_VAR resource = ~d5shc3f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 8   opcode = 177 parameter1 = 4 parameter2 = 0 timing = 2 STR_VAR resource = ~d5shc4f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 16  opcode = 177 parameter1 = 5 parameter2 = 0 timing = 2 STR_VAR resource = ~d5shc5f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 32  opcode = 177 parameter1 = 6 parameter2 = 0 timing = 2 STR_VAR resource = ~d5shc6f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 64  opcode = 177 parameter1 = 7 parameter2 = 0 timing = 2 STR_VAR resource = ~d5shc7f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 128 opcode = 177 parameter1 = 8 parameter2 = 0 timing = 2 STR_VAR resource = ~d5shc8f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 256 opcode = 177 parameter1 = 9 parameter2 = 0 timing = 2 STR_VAR resource = ~d5shc9f~ insert = ~first~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 1   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l1dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 2   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l2dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 4   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l3dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 8   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l4dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 16  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l5dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 32  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l6dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 64  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l7dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 128 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l8dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 256 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l9dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 1   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l1dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 2   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l2dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 4   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l3dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 8   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l4dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 16  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l5dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 32  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l6dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 64  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l7dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 128 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l8dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 256 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l9dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 1 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl1dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 2 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl2dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 3 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl3dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 4 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl4dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 5 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl5dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 6 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl6dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 7 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl7dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 8 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl8dsp~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 62 match_parameter1 = 9 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl9dsp~ END
	LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 202 parameter2 = 115 timing = 2 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5shplz~ END
  IF_EXISTS BUT_ONLY
 END

END // end if not already done

*/

END	//	end function


//___________________________________________________________________________________
//___________________________________________________________________________________

