
// NEW SPHERE NAMES___________________________________________________________________
//
// You can define the names of your spheres in the right-hand column
// There can be 23 spheres at most; they must correspond to the FnP spheres
// So DO NOT change anything in the left column.

<<<<<<<< d5/d5altsph.2da
2DA
Life 			Healing
Death 			Necromantic
Benediction 	Creation
Destruction 	Harm
Protection 		Protection
War 			Combat
Exploration     Travelers
Knowledge 		Divination
Deception 		Wards
Thought 		Thought
Dread 			Charm
Vigor 			Law
Affliction 		Chaos
Animal 			Animal
Plant 			Plant
Earth 			Earth
Air 			Air
Water 			Water
Fire 			Fire
Light 			Sun
Shadow 			Shadow
Magic 			Weather
Perdition 		Astral
>>>>>>>> 
COPY ~d5/d5altsph.2da~ ~override~

//____________________________________________________________________________________


// NEW SPHERE DEFINITIONS_____________________________________________________________
//
// The right-hand column defines which sphere a spell belongs to.  
// Use the names in the right column above.
//
// The left-hand column can include filenames (e.g. "sppr101") *OR* IDS names (e.g. "CLERIC_BLESS").

ACTION_DEFINE_ASSOCIATIVE_ARRAY alt_spheres BEGIN

//  UNIVERSAL
// 	universal spells will be available to every kit, regardless of their defined sphere assignments
// 	this "sphere" MUST MUST MUST have at least one spell of each spell level
// 	and their spell level MUST NOT be changed from the vanilla game (leave at 0 here)
// 	those are the rules you MUST abide by if you want to change which spells are universal

//Universal/all
CLERIC_BLESS                           , 0 => Universal
CLERIC_CURSE                           , 0 => Universal
CLERIC_CHANT                           , 0 => Universal
CLERIC_REMOVE_CURSE                    , 0 => Universal
CLERIC_DISPEL_MAGIC                    , 0 => Universal
CLERIC_PRAYER                          , 0 => Universal
CLERIC_RECITATION                      , 0 => Universal
CLERIC_RIGHTEOUS_WRATH_OF_THE_FAITHFUL , 0 => Universal
//SR_WIZARD_DEATH_SPELL                , 0 => Universal //sr banishment
CLERIC_WONDROUS_RECALL                 , 0 => Universal
CLERIC_HOLY_WORD                       , 0 => Universal
CLERIC_UNHOLY_WORD                     , 0 => Universal

//  "Healing"
CLERIC_CURE_LIGHT_WOUNDS               , 0 => Healing 
CLERIC_SLOW_POISON                     , 0 => Healing  //B_Spells protection from  - 2nd level protection
CLERIC_CURE_MODERATE_WOUNDS            , 0 => Healing  //SR accounted for
CLERIC_CURE_MEDIUM_WOUNDS              , 0 => Healing
CLERIC_EXALTATION                      , 0 => Healing
CLERIC_CURE_DISEASE                    , 0 => Healing
CLERIC_CURE_SERIOUS_WOUNDS             , 0 => Healing
CLERIC_NEUTRALIZE_POISON               , 0 => Healing
CLERIC_CURE_CRITICAL_WOUNDS            , 0 => Healing
CLERIC_MASS_CURE                       , 0 => Healing
CLERIC_HEAL                            , 0 => Healing
CLERIC_REGENERATE                      , 0 => Healing
CLERIC_RESTORATION                     , 0 => Healing
CLERIC_RESURRECTION                    , 0 => Healing

//  "Necromantic"
CLERIC_EYES_OF_THE_DEAD                , 0 => Necromantic
CLERIC_DISRUPT_UNDEAD                  , 0 => Necromantic
CLERIC_PACIFY_DEAD                     , 0 => Necromantic
CLERIC_CIRCLE_OF_BONES                 , 0 => Necromantic  //Sr accounted for
CLERIC_FAVOR_OF_ILMATER                , 0 => Necromantic
CLERIC_ANIMATE_DEAD                    , 0 => Necromantic
CLERIC_DEATH_WARD                      , 0 => Necromantic
CLERIC_NEGATIVE_PLANE_PROTECTION       , 0 => Necromantic
CLERIC_LESSER_RESTORATION              , 0 => Necromantic
CLERIC_RAISE_DEAD                      , 0 => Necromantic
CLERIC_REPULSE_UNDEAD                  , 0 => Necromantic  // SR repulsion
B_W631                                 , 0 => Necromantic  //soul eater (needed???)
//SR_WIZARD_CARRION                    , 0 => Death //sr skeleton warrior
CLERIC_SYMBOL_DEATH                    , 0 => Necromantic
CLERIC_FINGER_OF_DEATH                 , 0 => Necromantic

//  "Creation"
CLERIC_ABUNDANT_AMMO                   , 0 => Creation
CLERIC_BLESS_WATER                     , 0 => Creation
CLERIC_BINDING                         , 0 => Creation
//Divine Symbol                        , 0 => Creation //NEW SPELL
WIZARD_GREASE                          , 0 => Creation //NEW SPELL   (as wiz spell, or sim)
WIZARD_WEB                             , 0 => Creation //NEW SPELL
//Disable Construct                    , 0 => Creation //NEW SPELL http://www.d20pfsrd.com/magic/all-spells/d/disable-construct no save 1st round. Save each round after
//Vesting                              , 0 => Creation //NEW SPELL
//Heroes' feast                        , 0 => Creation //NEW SPELL
//Animate Object                       , 0 => Creation //NEW SPELL

//  "Destruction"
CLERIC_CAUSE_LIGHT_WOUNDS              , 0 => Destruction
CLERIC_CAUSE_DISEASE                   , 0 => Destruction  //SR accounted for
CLERIC_CAUSE_MODERATE_WOUNDS           , 0 => Destruction  //SR accounted for
WIZARD_BLINDNESS                       , 0 => Destruction
WIZARD_RAY_OF_ENFEEBLEMENT             , 0 => Destruction
CLERIC_MOLD_TOUCH                      , 0 => Destruction
CLERIC_CAUSE_MEDIUM_WOUNDS             , 0 => Destruction
CLERIC_CAUSE_SERIOUS_WOUNDS            , 0 => Destruction
CLERIC_POISON                          , 0 => Destruction
CLERIC_CAUSE_CRITICAL_WOUNDS           , 0 => Destruction
CLERIC_MASS_CAUSE_LIGHT_WOUNDS         , 0 => Destruction  //SR accounted for
CLERIC_SLAY_LIVING                     , 0 => Destruction
CLERIC_HARM                            , 0 => Destruction
CLERIC_DOLOROUS_DECAY                  , 0 => Destruction
CLERIC_WITHER                          , 0 => Destruction
CLERIC_DESTRUCTION                     , 0 => Destruction

//  "Protection"
CLERIC_PROTECT_FROM_EVIL               , 0 => Protection
CLERIC_SANCTUARY                       , 0 => Protection
CLERIC_ARMOR_OF_FAITH                  , 0 => Protection
CLERIC_RESIST_FIRE_AND_COLD            , 0 => Protection
//B_CLERIC_SLOW_POISON                 , 0 => Protection  //B_Spells protection from poison/disease
CLERIC_SPIRITUAL_CLARITY               , 0 => Protection
CLERIC_FAVOR_OF_ILMATER                , 0 => Protection
CLERIC_PROTECTION_FROM_EVIL_10_FOOT    , 0 => Protection
CLERIC_WALL_OF_MOONLIGHT               , 0 => Protection
//SR_CLERIC_REPULSE_UNDEAD             , 0 => Protection // SR repulsion
CLERIC_MAGIC_RESISTANCE                , 0 => Protection
CLERIC_PHYSICAL_MIRROR                 , 0 => Protection
CLERIC_SHIELD_OF_THE_ARCHONS           , 0 => Protection
CLERIC_GREATER_SHIELD_OF_LATHANDER     , 0 => Protection

//  "Combat"
CLERIC_HAND_OF_CARNAGE                 , 0 => Combat
CLERIC_MAGIC_WEAPON                    , 0 => Combat
CLERIC_ALICORN_LANCE                   , 0 => Combat
CLERIC_SPIRITUAL_HAMMER                , 0 => Combat
//Forced match                         , 0 => Combat //NEW SPELL
CLERIC_DRAW_UPON_HOLY_MIGHT            , 0 => Combat
CLERIC_HOLY_SMITE                      , 0 => Combat
CLERIC_UNHOLY_BLIGHT                   , 0 => Combat
CLERIC_HOLY_POWER                      , 0 => Combat
CLERIC_STAR_METAL_CUDGEL               , 0 => Combat
CLERIC_RIGHTEOUS_MAGIC                 , 0 => Combat
CLERIC_BLADE_BARRIER                   , 0 => Combat
CLERIC_BOLT_OF_GLORY                   , 0 => Combat
CLERIC_SPIRITUAL_WRATH                 , 0 => Combat

//  "Travelers"
//Dash (3x move 1 r)                   , 0 => Travelers // NEW SPELL
//Liberation                           , 0 => Travelers // NEW SPELL  (save to remove hold like effects)
CLERIC_REMOVE_PARALYSIS                , 0 => Travelers
//Longstrider                          , 0 => Travelers // NEW SPELL  (2x move 8 hr)
CLERIC_FREE_ACTION                     , 0 => Travelers
//Dimensional Jump                     , 0 => Travelers // NEW SPELL (as wiz)
CLERIC_UNFAILING_ENDURANCE             , 0 => Travelers
//Clear the Path                       , 0 => Travelers // NEW SPELL
WIZARD_TELEPORT_FIELD                  , 0 => Travelers

//  "Divination"
WIZARD_INFRAVISION                     , 0 => Divination // SR true strike no need to change
CLERIC_DETECT_EVIL                     , 0 => Divination
CLERIC_FIND_TRAPS                      , 0 => Divination
CLERIC_KNOW_ALIGNMENT                  , 0 => Divination // SR know opponent no need to change
WIZARD_CLAIRVOYANCE                    , 0 => Divination
CLERIC_INVISIBILITY_PURGE              , 0 => Divination
CLERIC_FAR_SIGHT                       , 0 => Divination
WIZARD_DETECT_ILLUSION                 , 0 => Divination
WIZARD_ORACLE                          , 0 => Divination
//Foresight                            , 0 => Divination //NEW SPELL
CLERIC_TRUE_SIGHT                      , 0 => Divination
WIZARD_CONTINGENCY                     , 0 => Divination

//  "Wards"
CLERIC_SPIRIT_WARD                     , 0 => Wards     // modify to work against all planar creatures, maybe undead too?
CLERIC_SILENCE_15_FOOT                 , 0 => Wards
CLERIC_ZONE_OF_SWEET_AIR               , 0 => Wards
CLERIC_GLYPH_OF_WARDING                , 0 => Wards
CLERIC_SHIELD_OF_LATHANDER             , 0 => Wards
CLERIC_UNDEAD_WARD                     , 0 => Wards
CLERIC_SPIRITUAL_LOCK                  , 0 => Wards
CLERIC_SYMBOL_FEAR                     , 0 => Wards // SR symbol weakness no need to change
CLERIC_SYMBOL_DEATH                    , 0 => Wards

//  "Thought"
CLERIC_COMMAND                         , 0 => Thought
CLERIC_FORBID                          , 0 => Thought
CLERIC_DICTATE                         , 0 => Thought
//Agonizing rebuke                     , 0 => Thought //NEW SPELL
CLERIC_MENTAL_DOMINATION               , 0 => Thought
CLERIC_GREATER_COMMAND                 , 0 => Thought
CLERIC_IMPERVIOUS_SANCTITY_OF_MIND     , 0 => Thought

//  "Charm"
CLERIC_DOOM                            , 0 => Charm
CLERIC_REMOVE_FEAR                     , 0 => Charm
CLERIC_ENTHRALL                        , 0 => Charm
//Compassion                           , 0 => Charm// NEW SPELL
CLERIC_HOLD_PERSON                     , 0 => Charm
CLERIC_CLOAK_OF_FEAR                   , 0 => Charm
b_w427                                 , 0 => Charm  //Emotion: Courage
b_w428                                 , 0 => Charm  //Emotion: Fear
b_w429                                 , 0 => Charm  //Emotion: Hope
CLERIC_NATURE_BEAUTY                   , 0 => Charm

//  "Law"
CLERIC_CASTIGATE                       , 0 => Law    // NEW SPELL http://www.d20pfsrd.com/magic/all-spells/c/castigate single target fear
CLERIC_STRENGTH_OF_ONE                 , 0 => Law
CLERIC_RIGID_THINKING                  , 0 => Law  //sr accounted for
CLERIC_DEFENSIVE_HARMONY               , 0 => Law
CLERIC_CHAMPIONS_STRENGTH              , 0 => Law
//Rebuke                               , 0 => Law // NEW SPELL http://www.d20pfsrd.com/magic/all-spells/r/rebuke

//  "Chaos"
CLERIC_MISCAST_MAGIC                   , 0 => Chaos
CLERIC_BLOOD_RAGE                      , 0 => Chaos
CLERIC_CHAOTIC_COMMANDS                , 0 => Chaos
CLERIC_ENTROPY_SHIELD                  , 0 => Chaos
CLERIC_CONFUSION                       , 0 => Chaos

//  "Animal"
CLERIC_ANIMAL_EYES                     , 0 => Animal
CLERIC_HOLD_ANIMAL                     , 0 => Animal
//CLERIC_ANIMAL_SUMMONING_SR_LEVEL_1   , 0 => Animal  // SR (present and future versions) accounted for
//CLERIC_ANIMAL_SUMMONING_SR_LEVEL_2   , 0 => Animal // SR (present and future versions) accounted for
CLERIC_BEAST_CLAW                      , 0 => Animal   //SR accounted for
CLERIC_CHARM_PERSON                    , 0 => Animal
//CLERIC_ANIMAL_SUMMONING_SR_LEVEL_3   , 0 => Animal // SR (present and future versions) accounted for
CLERIC_MAGIC_FANG                      , 0 => Animal    // SR (present and future versions) accounted for
CLERIC_SUMMON_INSECTS                  , 0 => Animal
CLERIC_FERAL_INSTINCT                  , 0 => Animal
CLERIC_ANIMAL_SUMMONING_1              , 0 => Animal
CLERIC_GIANT_INSECT                    , 0 => Animal
CLERIC_ANIMAL_SUMMONING_2              , 0 => Animal
CLERIC_INSECT_PLAGUE                   , 0 => Animal
CLERIC_ANIMAL_RAGE                     , 0 => Animal
CLERIC_ANIMAL_SUMMONING_3              , 0 => Animal
CLERIC_CONJURE_ANIMALS                 , 0 => Animal
CLERIC_CREEPING_DOOM                   , 0 => Animal
//CLERIC_ANIMAL_SUMMONING_SR_7         , 0 => Animal  // SR (present and future versions) accounted for

//  "Plant"
CLERIC_ENTANGLE                        , 0 => Plant
CLERIC_SHILLELAGH                      , 0 => Plant
CLERIC_GOODBERRY                       , 0 => Plant //Disable if SR installed
//SR_CLERIC_GOODBERRY_DRUID_VERSION    , 0 => Plant //SR version- Enable if SR installed
CLERIC_BARKSKIN                        , 0 => Plant
CLERIC_THORN_SPRAY                     , 0 => Plant
CLERIC_MOLD_TOUCH                      , 0 => Plant
CLERIC_SNARE                           , 0 => Plant
CLERIC_SPIKE_GROWTH                    , 0 => Plant  //SR accounted for
CLERIC_CALL_WOODLAND_BEINGS            , 0 => Plant
CLERIC_NATURES_WRATH                   , 0 => Plant
d5pr601 /*nature's wrath*/             , 0 => Plant
CLERIC_ASSASSIN_VINES                  , 0 => Plant
CLERIC_STALKER                         , 0 => Plant

//  "Elemental Earth"
CLERIC_MAGIC_STONE                     , 0 => Earth
CLERIC_CAMOUFLAGE                      , 0 => Earth
CLERIC_STONE_FIST                      , 0 => Earth
CLERIC_SPIKE_STONES                    , 0 => Earth
CLERIC_IRONSKIN                        , 0 => Earth
WIZARD_STONE_TO_FLESH                  , 0 => Earth
CLERIC_CONJURE_EARTH_ELEMENTAL         , 0 => Earth
WIZARD_FLESH_TO_STONE                  , 0 => Earth
CLERIC_EARTHQUAKE                      , 0 => Earth

//  "Elemental Air"
//SR_CLERIC_OBSCURING_MIST             , 0 => Air // Sr SPELL
// Wispering wind                      , 0 => Air // NEW SPELL as aud glammer
WIZARD_STINKING_CLOUD                  , 0 => Air
CLERIC_ZONE_OF_SWEET_AIR               , 0 => Air
//Gaseous form                         , 0 => Air // NEW SPELL http://www.d20pfsrd.com/magic/all-spells/g/gaseous-form no attack, slow move, almost invulnerable, wind spells push
CLERIC_CLOUD_OF_PESTILENCE             , 0 => Air
CLERIC_WHIRLWIND                       , 0 => Air
//winds of vengeance                   , 0 => Air  // NEW SPELL http://www.d20pfsrd.com/magic/all-spells/w/winds-of-vengeance


//  "Elemental Water"
CLERIC_FROST_FINGERS                   , 0 => Water
CLERIC_WATERY_FIST                     , 0 => Water
CLERIC_ICE_BLADE                       , 0 => Water
b_w204                                 , 0 => Water //Snowball Swarm
CLERIC_CLOUDBURST                      , 0 => Water
b_w327                                 , 0 => Water   //icelance
CLERIC_SMASHING_WAVE                   , 0 => Water
b_w432                                 , 0 => Water //v sphere
WIZARD_ICE_STORM                       , 0 => Water
CLERIC_MIST_OF_ELDATH                  , 0 => Water
CLERIC_CONJURE_WATER_ELEMENTAL         , 0 => Water
b_w724                                 , 0 => Water  //acid storm

//  "Elemental Fire"
CLERIC_FLAME_BLADE                     , 0 => Fire
CLERIC_PROTECTION_FROM_FIRE            , 0 => Fire
CLERIC_PRODUCE_FIRE                    , 0 => Fire   //SR accounted for
CLERIC_FLAME_STRIKE                    , 0 => Fire
CLERIC_CONJURE_FIRE_ELEMENTAL          , 0 => Fire
CLERIC_FIRE_SEEDS                      , 0 => Fire
CLERIC_FIRE_STORM                      , 0 => Fire

//  "Sun"
CLERIC_SUNSCORCH                       , 0 => Sun
//SR_CLERIC_FAERIE_FIRE                , 0 => Sun // Enable in SR
//Blinding Ray                         , 0 => Sun // NEW SPELL
CLERIC_MOONBLADE                       , 0 => Sun
CLERIC_WALL_OF_MOONLIGHT               , 0 => Sun
CLERIC_FALSE_DAWN                      , 0 => Sun
CLERIC_SOL_SEARING_ORB                 , 0 => Sun
CLERIC_SUNRAY                          , 0 => Sun

//  "Shadow"
b_w206                                 , 0 => Shadow  //Blindness (and no conflicts with SR)
CLERIC_CLOAK_DARKNESS                  , 0 => Shadow
b_w426                                 , 0 => Shadow  //Shadow Monsters
WIZARD_PHANTOM_BLADE                   , 0 => Shadow
WIZARD_SHADOW_DOOR                     , 0 => Shadow
d5sh501 /*SR summon shadows*/          , 0 => Shadow
B_SSTEP /*shadowstep*/                 , 0 => Shadow
B_W629                                 , 0 => Shadow //Shades
CLERIC_PIXIE_DUST                      , 0 => Shadow
WIZARD_POWER_WORD_BLIND                , 0 => Shadow

//  "Weather"
CLERIC_STORM_SHELL                     , 0 => Weather
CLERIC_CALL_LIGHTNING                  , 0 => Weather
CLERIC_PROTECTION_FROM_LIGHTNING       , 0 => Weather
CLERIC_STATIC_CHARGE                   , 0 => Weather
CLERIC_STORMWALL                       , 0 => Weather
WIZARD_ICE_STORM                       , 0 => Weather
WIZARD_CHAIN_LIGHTNING                 , 0 => Weather

//  "Astral"
CLERIC_WRITHING_FOG                    , 0 => Astral
CLERIC_SPIRIT_FIRE                     , 0 => Astral
CLERIC_RECALL_SPIRIT                   , 0 => Astral
CLERIC_AERIAL_SERVANT                  , 0 => Astral

END
//___________________________________________________________________________________


// VANILLA KIT SPHERE ASSIGNMENTS_____________________________________________________


// FnP KIT SPHERE ASSIGNMENTS_________________________________________________________

// UR-PRIEST__________________________________________________________________________
//
DEFINE_ACTION_MACRO ur_priest_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_clur_spheres BEGIN
	Healing		 		=> x
	Necromantic		 	=> major
	Creation			=> x
	Destruction		 		=> major
	Protection		 	=> major
	Combat		 		=> major
	Travelers		  	=> major
	Divination		 	=> major
	Wards	 			=> x
	Thought		 		=> major
	Charm		 		=> major
	Law		 		=> major
	Chaos		 		=> major
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> minor
	Water		 		=> minor
	Air		 		=> minor
	Fire		 		=> minor
	Sun	 			=> major
	Shadow		 		=> major
	Weather		 		=> major
	Astral		    	        => x
 END
END
//___________________________________________________________________________________

// CLERIC OF LATHANDER________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_lathander_spheres BEGIN
  ACTION_DEFINE_ASSOCIATIVE_ARRAY b_clat_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation			=> major
	Destruction			 	=> x
	Protection		 	=> major
	War		 		=> minor
	Travelers		  	=> minor
	Divination		 	=> minor
	Wards		 		=> x
	Thought		 		=> minor
	Charm		 		=> x
	Law			 	=> major
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 		=> minor
	Fire		 		=> major
	Sun		 		=> major
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			        => x
  END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_torm_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ctor_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> major
	Creation			=> major
	Destruction			 	=> minor
	Protection		 	=> focus
	War		 		=> major
	Travelers		  	=> minor
	Divination		 	=> minor
	Wards		 		=> x
	Thought		 		=> major
	Charm		 		=> minor
	Law			 	=> major
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 		=> x
	Fire		 		=> x
	Sun		 		=> minor
	Shadow		 		=> x
	Weather		 		=> x
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO fighter_cleric_torm_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_2tor_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> major
	Creation			=> major
	Destruction			 	=> minor
	Protection		 	=> focus
	War		 		=> major
	Travelers		  	=> minor
	Divination		 	=> minor
	Wards		 		=> x
	Thought		 		=> major
	Charm		 		=> minor
	Law			 	=> major
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 		=> x
	Fire		 		=> x
	Sun		 		=> minor
	Shadow		 		=> x
	Weather		 		=> x
	Astral			        => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_tymora_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5ctym_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> minor
	Protection		 	=> major
	War		 			=> x
	Travelers		  	=> major
	Divination		 	=> minor
	Wards		 		=> minor
	Thought		 		=> major
	Charm		 		=> minor
	Law			 		=> minor
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> major
	Fire		 		=> x
	Sun		 			=> major
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_thief_tymora_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d52tym_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> minor
	Protection		 	=> major
	War		 			=> x
	Travelers		  	=> major
	Divination		 	=> minor
	Wards		 		=> minor
	Thought		 		=> major
	Charm		 		=> minor
	Law			 		=> minor
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> major
	Fire		 		=> x
	Sun		 			=> major
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_helm_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_chel_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> minor
	Creation					=> major
	Destruction			 	=> major
	Protection		 	=> major
	War		 			=> major
	Travelers		  	=> minor
	Divination		 	=> major
	Wards		 		=> x
	Thought		 		=> minor
	Charm		 		=> minor
	Law			 		=> major
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> minor
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_kelemvor_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ckel_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> major
	Creation					=> x
	Destruction			 	=> x
	Protection		 	=> major
	War		 			=> major
	Travelers		  	=> minor
	Divination		 	=> major
	Wards		 		=> x
	Thought		 		=> minor
	Charm		 		=> major
	Law			 		=> x
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> minor
	Water		 		=> minor
	Air		 			=> x
	Fire		 		=> minor
	Sun		 			=> x
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => major
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_mage_kelemvor_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_cmkel_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> major
	Creation					=> x
	Destruction			 	=> x
	Protection		 	=> major
	War		 			=> major
	Travelers		  	=> minor
	Divination		 	=> major
	Wards		 		=> x
	Thought		 		=> minor
	Charm		 		=> major
	Law			 		=> x
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> minor
	Water		 		=> minor
	Air		 			=> x
	Fire		 		=> minor
	Sun		 			=> x
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => major
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO fighter_cleric_kelemvor_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_cfkel_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> major
	Creation					=> x
	Destruction			 	=> x
	Protection		 	=> major
	War		 			=> major
	Travelers		  	=> minor
	Divination		 	=> major
	Wards		 		=> x
	Thought		 		=> minor
	Charm		 		=> major
	Law			 		=> x
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> minor
	Water		 		=> minor
	Air		 			=> x
	Fire		 		=> minor
	Sun		 			=> x
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => major
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_tempus_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ctem_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> major
	Protection		 	=> major
	War		 			=> major
	Travelers		  	=> minor
	Divination		 	=> minor
	Wards		 		=> x
	Thought		 		=> minor
	Charm		 		=> x
	Law			 		=> major
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> minor
	Water		 		=> x
	Air		 			=> minor
	Fire		 		=> x
	Sun		 			=> minor
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO fighter_cleric_tempus_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_2tem_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> major
	Protection		 	=> major
	War		 			=> major
	Travelers		  	=> minor
	Divination		 	=> minor
	Wards		 		=> x
	Thought		 		=> minor
	Charm		 		=> x
	Law			 		=> major
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> minor
	Water		 		=> x
	Air		 			=> minor
	Fire		 		=> x
	Sun		 			=> minor
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_leira_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5clei_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> x
	Protection		 	=> minor
	War		 			=> x
	Travelers		  	=> major
	Divination		 	=> major
	Wards		 		=> major
	Thought		 		=> major
	Charm		 		=> minor
	Law			 		=> minor
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> minor
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> major
	Shadow		 		=> minor
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_thief_leira_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d52lei_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> x
	Protection		 	=> minor
	War		 			=> x
	Travelers		  	=> major
	Divination		 	=> major
	Wards		 		=> major
	Thought		 		=> major
	Charm		 		=> minor
	Law			 		=> minor
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> minor
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> major
	Shadow		 		=> minor
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_baravar_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_bara_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> x
	Protection		 	=> minor
	War		 			=> x
	Travelers		  	=> major
	Divination		 	=> major
	Wards		 		=> major
	Thought		 		=> major
	Charm		 		=> minor
	Law			 		=> minor
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> minor
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> major
	Shadow		 		=> minor
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_thief_baravar_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_bart_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> x
	Protection		 	=> minor
	War		 			=> x
	Travelers		  	=> major
	Divination		 	=> major
	Wards		 		=> major
	Thought		 		=> major
	Charm		 		=> minor
	Law			 		=> minor
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> minor
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> major
	Shadow		 		=> minor
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_loviatar_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_clov_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> major
	Creation					=> minor
	Destruction			 	=> minor
	Protection		 	=> x
	War		 			=> minor
	Travelers		  	=> minor
	Divination		 	=> major
	Wards		 		=> minor
	Thought		 		=> major
	Charm		 		=> major
	Law			 		=> minor
	Chaos			 	=> major
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> minor
	Weather		 		=> x
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_thief_loviatar_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_2lov_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> major
	Creation					=> minor
	Destruction			 	=> minor
	Protection		 	=> x
	War		 			=> minor
	Travelers		  	=> minor
	Divination		 	=> major
	Wards		 		=> minor
	Thought		 		=> major
	Charm		 		=> major
	Law			 		=> minor
	Chaos			 	=> major
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> minor
	Weather		 		=> x
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_talos_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ctal_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> major
	Protection		 	=> major
	War		 			=> minor
	Travelers		  	=> major
	Divination		 	=> x
	Wards		 		=> x
	Thought		 		=> x
	Charm		 		=> minor
	Law			 		=> minor
	Chaos			 	=> minor
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> major
	Fire		 		=> major
	Sun		 			=> minor
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO fighter_cleric_talos_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_2tal_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> major
	Protection		 	=> major
	War		 			=> minor
	Travelers		  	=> major
	Divination		 	=> x
	Wards		 		=> x
	Thought		 		=> x
	Charm		 		=> minor
	Law			 		=> minor
	Chaos			 	=> minor
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> major
	Fire		 		=> major
	Sun		 			=> minor
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_mage_talos_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_3tal_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> major
	Protection		 	=> major
	War		 			=> minor
	Travelers		  	=> major
	Divination		 	=> x
	Wards		 		=> x
	Thought		 		=> x
	Charm		 		=> minor
	Law			 		=> minor
	Chaos			 	=> minor
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> major
	Fire		 		=> major
	Sun		 			=> minor
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_cyric_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ccyr_spheres BEGIN
	Healing		 		=> minor
	Necromantic	 		=> major
	Creation					=> minor
	Destruction			 	=> major
	Protection		 	=> x
	War		 			=> x
	Travelers		  	=> minor
	Divination		 	=> x
	Wards		 		=> major
	Thought		 		=> minor
	Charm		 		=> major
	Law			 		=> minor
	Chaos			 	=> major
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> major
	Weather		 		=> minor
	Astral			    => major
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_thief_cyric_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ctcyr_spheres BEGIN
	Healing		 		=> minor
	Necromantic	 		=> major
	Creation					=> minor
	Destruction			 	=> major
	Protection		 	=> x
	War		 			=> x
	Travelers		  	=> minor
	Divination		 	=> x
	Wards		 		=> major
	Thought		 		=> minor
	Charm		 		=> major
	Law			 		=> minor
	Chaos			 	=> major
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> major
	Weather		 		=> minor
	Astral			    => major
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cleric_umberlee_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_umb_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> major
	Protection		 	=> major
	War		 			=> minor
	Travelers		  	=> major
	Divination		 	=> minor
	Wards		 		=> x
	Thought		 		=> x
	Charm		 		=> major
	Law			 		=> minor
	Chaos			 	=> minor
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> focus
	Air		 			=> major
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_ilmater_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ailm_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> minor
	Protection		 	=> focus
	War		 			=> x
	Travelers		  	=> x
	Divination		 	=> major
	Wards		 		=> x
	Thought		 		=> minor
	Charm		 		=> minor
	Law			 		=> major
	Chaos			 	=> major
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> minor
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_deneir_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_aden_spheres BEGIN
	Healing		 		=> minor
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> x
	Protection		 	=> major
	War		 			=> x
	Travelers		  	=> minor
	Divination		 	=> focus
	Wards		 		=> minor
	Thought		 		=> major
	Charm		 		=> minor
	Law			 		=> minor
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> major
	Shadow		 		=> x
	Weather		 		=> major
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_cm_deneir_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_2den_spheres BEGIN
	Healing		 		=> minor
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> x
	Protection		 	=> major
	War		 			=> x
	Travelers		  	=> minor
	Divination		 	=> focus
	Wards		 		=> minor
	Thought		 		=> major
	Charm		 		=> minor
	Law			 		=> minor
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> major
	Shadow		 		=> x
	Weather		 		=> major
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_sune_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_asun_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> x
	Protection		 	=> minor
	War		 			=> x
	Travelers		  	=> minor
	Divination		 	=> major
	Wards		 		=> major
	Thought		 		=> focus
	Charm		 		=> major
	Law			 		=> major
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> minor
	Shadow		 		=> minor
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_ct_sune_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_2sun_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> x
	Protection		 	=> minor
	War		 			=> x
	Travelers		  	=> minor
	Divination		 	=> major
	Wards		 		=> major
	Thought		 		=> focus
	Charm		 		=> major
	Law			 		=> major
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> minor
	Shadow		 		=> minor
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_cm_sune_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_3sun_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> x
	Protection		 	=> minor
	War		 			=> x
	Travelers		  	=> minor
	Divination		 	=> major
	Wards		 		=> major
	Thought		 		=> focus
	Charm		 		=> major
	Law			 		=> major
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> minor
	Shadow		 		=> minor
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_tempus_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_atem_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> minor
	Creation					=> major
	Destruction			 	=> major
	Protection		 	=> major
	War		 			=> focus
	Travelers		  	=> minor
	Divination		 	=> x
	Wards		 		=> x
	Thought		 		=> x
	Charm		 		=> minor
	Law			 		=> major
	Chaos			 	=> minor
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> minor
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> minor
	Sun		 			=> x
	Shadow		 		=> x
	Weather		 		=> x
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_mystra_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5acmys_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> major
	Protection		 	=> major
	War		 			=> x
	Travelers		  	=> minor
	Divination		 	=> major
	Wards		 		=> x
	Thought		 		=> minor
	Charm		 		=> minor
	Law			 		=> minor
	Chaos			 	=> x
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> minor
	Sun		 			=> major
	Shadow		 		=> minor
	Weather		 		=> focus
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_mask_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5amas_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> minor
	Creation					=> minor
	Destruction			 	=> major
	Protection		 	=> minor
	War		 			=> x
	Travelers		  	=> x
	Divination		 	=> major
	Wards		 		=> major
	Thought		 		=> minor
	Charm		 		=> major
	Law			 		=> x
	Chaos			 	=> minor
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> focus
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_ct_mask_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d52mas_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> minor
	Creation					=> minor
	Destruction			 	=> major
	Protection		 	=> minor
	War		 			=> x
	Travelers		  	=> x
	Divination		 	=> major
	Wards		 		=> major
	Thought		 		=> minor
	Charm		 		=> major
	Law			 		=> x
	Chaos			 	=> minor
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> focus
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_shar_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5asha_spheres BEGIN
	Healing		 		=> minor
	Necromantic	 		=> major
	Creation					=> x
	Destruction			 	=> major
	Protection		 	=> minor
	War		 			=> x
	Travelers		  	=> x
	Divination		 	=> minor
	Wards		 		=> minor
	Thought		 		=> minor
	Charm		 		=> major
	Law			 		=> x
	Chaos			 	=> minor
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> focus
	Weather		 		=> major
	Astral			    => major
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_cm_shar_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d52sha_spheres BEGIN
	Healing		 		=> minor
	Necromantic	 		=> major
	Creation					=> x
	Destruction			 	=> major
	Protection		 	=> minor
	War		 			=> x
	Travelers		  	=> x
	Divination		 	=> minor
	Wards		 		=> minor
	Thought		 		=> minor
	Charm		 		=> major
	Law			 		=> x
	Chaos			 	=> minor
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> focus
	Weather		 		=> major
	Astral			    => major
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_ct_shar_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ctshr_spheres BEGIN
	Healing		 		=> minor
	Necromantic	 		=> major
	Creation					=> x
	Destruction			 	=> major
	Protection		 	=> minor
	War		 			=> x
	Travelers		  	=> x
	Divination		 	=> minor
	Wards		 		=> minor
	Thought		 		=> minor
	Charm		 		=> major
	Law			 		=> x
	Chaos			 	=> minor
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> focus
	Weather		 		=> major
	Astral			    => major
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_moander_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_cmoa_spheres BEGIN
	Healing		 		=> x
	Necromantic	 		=> major
	Creation					=> x
	Destruction			 	=> major
	Protection		 	=> x
	War		 			=> x
	Travelers		  	=> minor
	Divination		 	=> x
	Wards		 		=> minor
	Thought		 		=> x
	Charm		 		=> major
	Law			 		=> minor
	Chaos			 	=> major
	Animal		 		=> minor
	Plant		 		=> focus
	Earth		 		=> major
	Water		 		=> minor
	Air		 			=> minor
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> major
	Weather		 		=> x
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_cm_moander_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_c2moa_spheres BEGIN
	Healing		 		=> x
	Necromantic	 		=> major
	Creation					=> x
	Destruction			 	=> major
	Protection		 	=> x
	War		 			=> x
	Travelers		  	=> minor
	Divination		 	=> x
	Wards		 		=> minor
	Thought		 		=> x
	Charm		 		=> major
	Law			 		=> minor
	Chaos			 	=> major
	Animal		 		=> minor
	Plant		 		=> focus
	Earth		 		=> major
	Water		 		=> minor
	Air		 			=> minor
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> major
	Weather		 		=> x
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_ct_moander_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_c3moa_spheres BEGIN
	Healing		 		=> x
	Necromantic	 		=> major
	Creation					=> x
	Destruction			 	=> major
	Protection		 	=> x
	War		 			=> x
	Travelers		  	=> minor
	Divination		 	=> x
	Wards		 		=> minor
	Thought		 		=> x
	Charm		 		=> major
	Law			 		=> minor
	Chaos			 	=> major
	Animal		 		=> minor
	Plant		 		=> focus
	Earth		 		=> major
	Water		 		=> minor
	Air		 			=> minor
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> major
	Weather		 		=> x
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_beshaba_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_abes_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> major
	Creation					=> major
	Destruction			 	=> minor
	Protection		 	=> major
	War		 			=> x
	Travelers		  	=> x
	Divination		 	=> minor
	Wards		 		=> minor
	Thought		 		=> major
	Charm		 		=> focus
	Law			 		=> minor
	Chaos			 	=> minor
	Animal		 		=> x
	Plant		 		=> x
	Earth		 		=> x
	Water		 		=> x
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> x
	Shadow		 		=> x
	Weather		 		=> minor
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_baervan_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5baerv_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> x
	Protection		 	=> major
	War		 			=> x
	Travelers		  	=> minor
	Divination		 	=> minor
	Wards		 		=> x
	Thought		 		=> minor
	Charm		 		=> x
	Law			 		=> minor
	Chaos			 	=> x
	Animal		 		=> focus
	Plant		 		=> major
	Earth		 		=> major
	Water		 		=> minor
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> minor
	Shadow		 		=> x
	Weather		 		=> x
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO acolyte_cm_baervan_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5baer2_spheres BEGIN
	Healing		 		=> major
	Necromantic	 		=> x
	Creation					=> major
	Destruction			 	=> x
	Protection		 	=> major
	War		 			=> x
	Travelers		  	=> minor
	Divination		 	=> minor
	Wards		 		=> x
	Thought		 		=> minor
	Charm		 		=> x
	Law			 		=> minor
	Chaos			 	=> x
	Animal		 		=> focus
	Plant		 		=> major
	Earth		 		=> major
	Water		 		=> minor
	Air		 			=> x
	Fire		 		=> x
	Sun		 			=> minor
	Shadow		 		=> x
	Weather		 		=> x
	Astral			    => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO druid_forest_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5dfor_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> minor
	Animal 			=> major
	Plant 			=> major
	Earth 			=> major
	Water 			=> major
	Air 			=> major
	Fire 			=> minor
	Sun	 			=> major
	Shadow 			=> minor
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO druid_totemic_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabdr02_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers   	=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> minor
	Animal 			=> major
	Plant 			=> major
	Earth 			=> major
	Water 			=> major
	Air 			=> major
	Fire 			=> minor
	Sun	 			=> major
	Shadow 			=> minor
	Weather 		=> x
	Astral	     	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO druid_hivekeeper_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabdr04_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers   	=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> major
	Animal 			=> minor
	Plant 			=> major
	Earth 			=> major
	Water 			=> major
	Air 			=> major
	Fire 			=> minor
	Sun	 			=> major
	Shadow 			=> minor
	Weather 		=> minor
	Astral	     	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO druid_northern_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5darc_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers   	=> major
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> minor
	Animal 			=> major
	Plant 			=> minor
	Earth 			=> major
	Water 			=> focus
	Air 			=> major
	Fire 			=> minor
	Sun	 			=> major
	Shadow 			=> minor
	Weather 		=> x
	Astral	     	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO druid_shadow_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5dshad_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers   	=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> minor
	Law	 			=> major
	Chaos	 		=> minor
	Animal 			=> major
	Plant 			=> major
	Earth 			=> major
	Water 			=> major
	Air 			=> major
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> major
	Weather 		=> x
	Astral	     	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO druid_gray_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5dgray_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers   	=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> minor
	Law	 			=> major
	Chaos	 		=> minor
	Animal 			=> major
	Plant 			=> major
	Earth 			=> major
	Water 			=> major
	Air 			=> major
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> major
	Weather 		=> x
	Astral	     	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO druid_lost_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5dlost_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> major
	Creation				=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers   	=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> minor
	Animal 			=> major
	Plant 			=> major
	Earth 			=> major
	Water 			=> major
	Air 			=> major
	Fire 			=> minor
	Sun	 			=> x
	Shadow 			=> minor
	Weather 		=> x
	Astral	     	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO druid_fighter_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5drfi_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers   	=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> minor
	Animal 			=> major
	Plant 			=> major
	Earth 			=> major
	Water 			=> major
	Air 			=> major
	Fire 			=> minor
	Sun	 			=> major
	Shadow 			=> minor
	Weather 		=> x
	Astral	     	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO druid_mage_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5drma_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers   	=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> minor
	Animal 			=> major
	Plant 			=> major
	Earth 			=> major
	Water 			=> major
	Air 			=> major
	Fire 			=> minor
	Sun	 			=> major
	Shadow 			=> minor
	Weather 		=> x
	Astral	     	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO druid_ranger_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5drra_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> minor
	Animal 			=> major
	Plant 			=> major
	Earth 			=> major
	Water 			=> major
	Air 			=> major
	Fire 			=> minor
	Sun	 			=> major
	Shadow 			=> minor
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO druid_thief_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5drth_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> minor
	Animal 			=> major
	Plant 			=> major
	Earth 			=> major
	Water 			=> major
	Air 			=> major
	Fire 			=> minor
	Sun	 			=> major
	Shadow 			=> minor
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO mystic_earth_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5mear_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> major
	Combat			=> x
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> minor
	Animal 			=> x
	Plant 			=> major
	Earth 			=> focus
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> major
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO mystic_warrior_earth_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5mear2_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> major
	Combat			=> x
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> minor
	Animal 			=> x
	Plant 			=> major
	Earth 			=> focus
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> major
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO mystic_water_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5mwat_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers		=> minor
	Divination 		=> x
	Wards	 		=> minor
	Thought 		=> x
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> major
	Animal 			=> minor
	Plant 			=> minor
	Earth 			=> x
	Water 			=> focus
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> major
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO mystic_warrior_water_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5mwat2_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers		=> minor
	Divination 		=> x
	Wards	 		=> minor
	Thought 		=> x
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> major
	Animal 			=> minor
	Plant 			=> minor
	Earth 			=> x
	Water 			=> focus
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> major
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO mystic_air_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5mair_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> minor
	Combat			=> x
	Travelers		=> major
	Divination 		=> major
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> focus
	Fire 			=> x
	Sun	 			=> minor
	Shadow 			=> x
	Weather 		=> major
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO mystic_warrior_air_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5mair2_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> minor
	Combat			=> x
	Travelers		=> major
	Divination 		=> major
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> focus
	Fire 			=> x
	Sun	 			=> minor
	Shadow 			=> x
	Weather 		=> major
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO mystic_fire_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5mfir_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> x
	Destruction			=> minor
	Protection 		=> major
	Combat			=> x
	Travelers		=> minor
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> minor
	Law	 			=> minor
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> focus
	Sun	 			=> major
	Shadow 			=> x
	Weather 		=> major
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO mystic_warrior_fire_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5mfir2_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> x
	Destruction			=> minor
	Protection 		=> major
	Combat			=> x
	Travelers		=> minor
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> minor
	Law	 			=> minor
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> focus
	Sun	 			=> major
	Shadow 			=> x
	Weather 		=> major
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO mystic_light_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5mlig_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> major
	Combat			=> x
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> major
	Thought 		=> x
	Charm 			=> x
	Law	 			=> minor
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> minor
	Fire 			=> minor
	Sun	 			=> focus
	Shadow 			=> x
	Weather 		=> major
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO mystic_warrior_light_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5mlig2_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> major
	Combat			=> x
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> major
	Thought 		=> x
	Charm 			=> x
	Law	 			=> minor
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> minor
	Fire 			=> minor
	Sun	 			=> focus
	Shadow 			=> x
	Weather 		=> major
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO mystic_shadow_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5mshd_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> minor
	Thought 		=> major
	Charm 			=> major
	Law	 			=> major
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> focus
	Weather 		=> major
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO mystic_warrior_shadow_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5mshd2_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> minor
	Thought 		=> major
	Charm 			=> major
	Law	 			=> major
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> focus
	Weather 		=> major
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO beast_lord_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5obst_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> minor
	Creation				=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers		=> major
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> major
	Charm 			=> minor
	Law	 			=> major
	Chaos	 		=> major
	Animal 			=> focus
	Plant 			=> x
	Earth 			=> x
	Water 			=> minor
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> minor
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO occultist_elementalist_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5oelm_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> minor
	Protection 		=> minor
	Combat			=> x
	Travelers		=> x
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> minor
	Law	 			=> minor
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> major
	Water 			=> major
	Air 			=> major
	Fire 			=> major
	Sun	 			=> major
	Shadow 			=> minor
	Weather 		=> minor
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO champion_tyr_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ch01_spheres BEGIN
	Healing 		=> paladin
	Necromantic		=> x
	Creation				=> paladin
	Destruction			=> x
	Protection  	=> paladin
	Combat			=> paladin
	Travelers		=> x
	Divination 		=> paladin
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> paladin
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> paladin
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO champion_kelemvor_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ch02_spheres BEGIN
	Healing 		=> paladin
	Necromantic		=> paladin
	Creation				=> x
	Destruction			=> x
	Protection		=> paladin
	Combat			=> paladin
	Travelers		=> x
	Divination 		=> paladin
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> paladin
	Law	 			=> x
	Chaos	 		=> paladin
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO champion_tempus_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ch03_spheres BEGIN
	Healing 		=> paladin
	Necromantic		=> x
	Creation		 	 	=> paladin
	Destruction	 	 	=> x
	Protection 	 	=> paladin
	Combat			=> paladin
	Travelers		=> x
	Divination 	 	=> paladin
	Wards	 	 	=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> paladin
	Chaos	 	 	=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> paladin
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO champion_bane_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ch04_spheres BEGIN
	Healing 		=> x
	Necromantic		=> paladin
	Creation				=> x
	Destruction			=> paladin
	Protection		=> x
	Combat			=> paladin
	Travelers		=> x
	Divination 		=> paladin
	Wards	 		=> x
	Thought 		=> paladin
	Charm 			=> paladin
	Law	 			=> x
	Chaos	 		=> paladin
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> paladin
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO champion_helm_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ch05_spheres BEGIN
	Healing 		=> paladin
	Necromantic		=> x
	Creation				=> paladin
	Destruction			=> x
	Protection		=> paladin
	Combat			=> paladin
	Travelers		=> paladin
	Divination 		=> paladin
	Wards	 		=> x
	Thought 		=> paladin
	Charm 			=> x
	Law	 			=> paladin
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO champion_talos_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ch06_spheres BEGIN
	Healing 		=> x
	Necromantic		=> paladin
	Creation				=> x
	Destruction			=> paladin
	Protection		=> paladin
	Combat			=> paladin
	Travelers		=> paladin
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> paladin
	Law	 			=> x
	Chaos	 		=> paladin
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> paladin
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO champion_moradin_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ch07_spheres BEGIN
	Healing 		=> paladin
	Necromantic		=> x
	Creation				=> paladin
	Destruction			=> x
	Protection		=> paladin
	Combat			=> paladin
	Travelers		=> x
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> paladin
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> paladin
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> paladin
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO champion_azuth_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ch08_spheres BEGIN
	Healing 		=> x
	Necromantic		=> x
	Creation				=> paladin
	Destruction			=> x
	Protection		=> paladin
	Combat			=> x
	Travelers		=> x
	Divination 		=> paladin
	Wards	 		=> x
	Thought 		=> paladin
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> paladin
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> paladin
	Fire 			=> paladin
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> paladin
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO champion_red_knight_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ch09_spheres BEGIN
	Healing 		=> paladin
	Necromantic		=> x
	Creation				=> paladin
	Destruction			=> x
	Protection		=> paladin
	Combat			=> paladin
	Travelers		=> x
	Divination 		=> paladin
	Wards	 		=> x
	Thought 		=> paladin
	Charm 			=> x
	Law	 			=> paladin
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO zealot_gruumsh_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ze02_spheres BEGIN
	Healing 		=> x
	Necromantic		=> ranger
	Creation				=> x
	Destruction			=> ranger
	Protection		=> ranger
	Combat			=> ranger
	Travelers		=> x
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> ranger
	Law	 			=> ranger
	Chaos	 		=> ranger
	Animal 			=> ranger
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_zgruu_spheres BEGIN
	Healing 		=> x
	Necromantic		=> ranger
	Creation				=> x
	Destruction			=> ranger
	Protection		=> ranger
	Combat			=> ranger
	Travelers		=> x
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> ranger
	Law	 			=> ranger
	Chaos	 		=> ranger
	Animal 			=> ranger
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO zealot_talos_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ze03_spheres BEGIN
	Healing 		=> x
	Necromantic		=> ranger
	Creation				=> x
	Destruction			=> ranger
	Protection		=> ranger
	Combat			=> ranger
	Travelers		=> x
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> ranger
	Law	 			=> x
	Chaos	 		=> ranger
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> ranger
	Fire 			=> ranger
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ztal_spheres BEGIN
	Healing 		=> x
	Necromantic		=> ranger
	Creation				=> x
	Destruction			=> ranger
	Protection		=> ranger
	Combat			=> ranger
	Travelers		=> x
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> ranger
	Law	 			=> x
	Chaos	 		=> ranger
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> ranger
	Fire 			=> ranger
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO zealot_kossuth_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ze04_spheres BEGIN
	Healing 		=> x
	Necromantic		=> x
	Creation				=> x
	Destruction			=> ranger
	Protection		=> ranger
	Combat			=> ranger
	Travelers		=> x
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> ranger
	Law	 			=> ranger
	Chaos	 		=> ranger
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> ranger
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_koss_spheres BEGIN
	Healing 		=> x
	Necromantic		=> x
	Creation				=> x
	Destruction			=> ranger
	Protection		=> ranger
	Combat			=> ranger
	Travelers		=> x
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> ranger
	Law	 			=> ranger
	Chaos	 		=> ranger
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> ranger
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO zealot_ilmater_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ze05_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> ranger
	Destruction			=> ranger
	Protection		=> ranger
	Combat			=> ranger
	Travelers		=> x
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> ranger
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_zilm_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> ranger
	Destruction			=> ranger
	Protection		=> ranger
	Combat			=> ranger
	Travelers		=> x
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> ranger
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO zealot_garagos_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ze06_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> ranger
	Destruction			=> ranger
	Protection		=> ranger
	Combat			=> ranger
	Travelers		=> x
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> ranger
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_gara_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> ranger
	Destruction			=> ranger
	Protection		=> ranger
	Combat			=> ranger
	Travelers		=> x
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> ranger
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO zealot_corellon_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ze07_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> ranger
	Destruction			=> x
	Protection		=> ranger
	Combat			=> ranger
	Travelers		=> x
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> ranger
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> ranger
	Astral	    	=> x
 END
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_zcor_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> ranger
	Destruction			=> x
	Protection		=> ranger
	Combat			=> ranger
	Travelers		=> x
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> ranger
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> ranger
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO zealot_sune_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ze08_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> ranger
	Destruction			=> x
	Protection		=> ranger
	Combat			=> x
	Travelers		=> x
	Divination 		=> ranger
	Wards	 		=> ranger
	Thought 		=> ranger
	Charm 			=> ranger
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_zsun_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> ranger
	Destruction			=> x
	Protection		=> ranger
	Combat			=> x
	Travelers		=> x
	Divination 		=> ranger
	Wards	 		=> ranger
	Thought 		=> ranger
	Charm 			=> ranger
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO zealot_mystra_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ze09_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> ranger
	Destruction			=> ranger
	Protection		=> ranger
	Combat			=> ranger
	Travelers		=> x
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> ranger
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_zmys_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> ranger
	Destruction			=> ranger
	Protection		=> ranger
	Combat			=> ranger
	Travelers		=> x
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> ranger
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO zealot_eilistraee_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_ze10_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> ranger
	Destruction			=> x
	Protection		=> ranger
	Combat			=> x
	Travelers		=> x
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> ranger
	Charm 			=> ranger
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> ranger
	Shadow 			=> ranger
	Weather 		=> x
	Astral	    	=> x
 END
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_zeil_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> ranger
	Destruction			=> x
	Protection		=> ranger
	Combat			=> x
	Travelers		=> x
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> ranger
	Charm 			=> ranger
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> ranger
	Shadow 			=> ranger
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO ranger_forest_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5rfor_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> ranger
	Combat			=> x
	Travelers		=> ranger
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> ranger
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> ranger
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO ranger_mountain_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5rmou_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> ranger
	Combat			=> x
	Travelers		=> ranger
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> x
	Earth 			=> ranger
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> ranger
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO ranger_desert_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5rdes_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> ranger
	Combat			=> x
	Travelers		=> ranger
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> ranger
	Fire 			=> x
	Sun	 			=> ranger
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO ranger_jungle_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5rjun_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> x
	Combat			=> x
	Travelers		=> ranger
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> ranger
	Animal 			=> x
	Plant 			=> ranger
	Earth 			=> x
	Water 			=> ranger
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> ranger
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO ranger_arctic_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5rarc_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> ranger
	Combat			=> x
	Travelers		=> ranger
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> x
	Earth 			=> x
	Water 			=> ranger
	Air 			=> ranger
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________


// ________________________________________________________________
//
DEFINE_ACTION_MACRO ranger_beastmaster_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabrn04_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> x
	Combat			=> x
	Travelers		=> ranger
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO barbarian_ranger_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5_rbarb_spheres BEGIN
	Healing 		=> x
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> x
	Combat			=> x
	Travelers		=> ranger
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO scout_mage_hunter_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5_mageh_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> ranger
	Combat			=> x
	Travelers		=> ranger
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> ranger
	Shadow 			=> x
	Weather 		=> ranger
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO scout_elven_archer_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5_earch_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> ranger
	Combat			=> x
	Travelers		=> ranger
	Divination 		=> ranger
	Wards	 		=> ranger
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> ranger
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> ranger
	Shadow 			=> x
	Weather 		=> ranger
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO scout_slinger_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5_sling_spheres BEGIN
	Healing 		=> x
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> ranger
	Combat			=> x
	Travelers		=> ranger
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> ranger
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cm_mystra_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5cmmys_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> major
	Destruction			=> major
	Protection		=> major
	Combat			=> x
	Travelers		=> minor
	Divination 		=> major
	Wards	 		=> minor
	Thought 		=> minor
	Charm 			=> x
	Law	 			=> minor
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> minor
	Sun	 			=> minor
	Shadow 			=> x
	Weather 		=> major
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cm_azuth_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5cmazu_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> major
	Destruction			=> major
	Protection		=> major
	Combat			=> x
	Travelers		=> minor
	Divination 		=> major
	Wards	 		=> minor
	Thought 		=> minor
	Charm 			=> minor
	Law	 			=> minor
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> minor
	Sun	 			=> major
	Shadow 			=> minor
	Weather 		=> major
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cm_spellbender_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5_bendr_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> major
	Protection		=> minor
	Combat			=> x
	Travelers		=> major
	Divination 		=> major
	Wards	 		=> minor
	Thought 		=> major
	Charm 			=> major
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> minor
	Shadow 			=> minor
	Weather 		=> major
	Astral	    	=> minor
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO fc_clangeddin_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5cfcla_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> major
	Destruction			=> minor
	Protection		=> major
	Combat			=> major
	Travelers		=> x
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> minor
	Law	 			=> major
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> major
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> minor
	Shadow 			=> x
	Weather 		=> minor
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cr_mielikki_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5crmi_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> major
	Destruction			=> x
	Protection		=> minor
	Combat			=> x
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> focus
	Chaos	 		=> minor
	Animal 			=> major
	Plant 			=> major
	Earth 			=> major
	Water 			=> minor
	Air 			=> minor
	Fire 			=> x
	Sun	 			=> minor
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO cr_shaundakul_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY d5crsh_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> minor
	Destruction			=> x
	Protection		=> major
	Combat			=> x
	Travelers		=> focus
	Divination 		=> major
	Wards	 		=> minor
	Thought 		=> x
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> x
	Animal 			=> minor
	Plant 			=> minor
	Earth 			=> x
	Water 			=> minor
	Air 			=> major
	Fire 			=> x
	Sun	 			=> major
	Shadow 			=> x
	Weather 		=> minor
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO fc_helm_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY b_cfhe_spheres BEGIN
	Healing 		=> major
	Necromantic		=> minor
	Creation				=> major
	Destruction			=> minor
	Protection		=> major
	Combat			=> major
	Travelers		=> minor
	Divination 		=> major
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> minor
	Law	 			=> major
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> minor
	Shadow 			=> x
	Weather 		=> minor
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// DEFAULT KIT SPHERE ASSIGNMENTS____________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_shaman_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabshgs_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> x
	Combat			=> x
	Travelers		=> x
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> major
	Plant 			=> major
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> major
	Weather 		=> x
	Astral	    	=> major
 END
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabsh01_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> x
	Combat			=> x
	Travelers		=> x
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> major
	Plant 			=> major
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> major
	Weather 		=> x
	Astral	    	=> major
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_cleric_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabpr01_spheres BEGIN
	Healing 		=> major
	Necromantic		=> minor
	Creation				=> major
	Destruction			=> major
	Protection		=> major
	Combat			=> minor
	Travelers		=> minor
	Divination 		=> major
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> major
	Law	 			=> minor
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> minor
	Sun	 			=> major
	Shadow 			=> x
	Weather 		=> minor
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_cleric_talos_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabpr02_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> major
	Destruction			=> major
	Protection		=> major
	Combat			=> minor
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> minor
	Law	 			=> minor
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> major
	Air 			=> major
	Fire 			=> x
	Sun	 			=> minor
	Shadow 			=> x
	Weather 		=> minor
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_cleric_helm_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabpr03_spheres BEGIN
	Healing 		=> major
	Necromantic		=> minor
	Creation				=> major
	Destruction			=> minor
	Protection		=> major
	Combat			=> major
	Travelers		=> minor
	Divination 		=> major
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> minor
	Law	 			=> major
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> minor
	Shadow 			=> x
	Weather 		=> minor
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_cleric_lathander_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabpr04_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> major
	Destruction			=> minor
	Protection		=> major
	Combat			=> minor
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> minor
	Fire 			=> major
	Sun	 			=> major
	Shadow 			=> x
	Weather 		=> minor
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_cleric_tyr_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY ohtyr_spheres BEGIN
	Healing 		=> major
	Necromantic		=> minor
	Creation				=> major
	Destruction			=> minor
	Protection		=> major
	Combat			=> major
	Travelers		=> x
	Divination 		=> major
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> minor
	Law	 			=> major
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> minor
	Shadow 			=> x
	Weather 		=> minor
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_cleric_tempus_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY ohtempus_spheres BEGIN
	Healing 		=> major
	Necromantic		=> x
	Creation				=> major
	Destruction			=> major
	Protection		=> major
	Combat			=> major
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> minor
	Water 			=> x
	Air 			=> minor
	Fire 			=> x
	Sun	 			=> minor
	Shadow 			=> x
	Weather 		=> minor
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_druid_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabdr01_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> x
	Combat			=> x
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> minor
	Animal 			=> major
	Plant 			=> major
	Earth 			=> major
	Water 			=> major
	Air 			=> major
	Fire 			=> minor
	Sun	 			=> major
	Shadow 			=> minor
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_druid_totemic_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabdr02_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> x
	Combat			=> x
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> minor
	Animal 			=> major
	Plant 			=> major
	Earth 			=> major
	Water 			=> major
	Air 			=> major
	Fire 			=> minor
	Sun	 			=> major
	Shadow 			=> minor
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_shapeshifter_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabdr03_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> x
	Combat			=> x
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> minor
	Charm 			=> minor
	Law	 			=> major
	Chaos	 		=> major
	Animal 			=> focus
	Plant 			=> major
	Earth 			=> minor
	Water 			=> minor
	Air 			=> minor
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> minor
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_avenger_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabdr04_spheres BEGIN
	Healing 		=> minor
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> x
	Combat			=> x
	Travelers		=> minor
	Divination 		=> minor
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> major
	Chaos	 		=> major
	Animal 			=> minor
	Plant 			=> major
	Earth 			=> major
	Water 			=> major
	Air 			=> major
	Fire 			=> minor
	Sun	 			=> major
	Shadow 			=> minor
	Weather 		=> minor
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_paladin_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabpa01_spheres BEGIN
	Healing 		=> paladin
	Necromantic		=> x
	Creation				=> paladin
	Destruction			=> paladin
	Protection		=> paladin
	Combat			=> paladin
	Travelers		=> x
	Divination 		=> paladin
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> paladin
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_paladin_cavalier_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabpa02_spheres BEGIN
	Healing 		=> paladin
	Necromantic		=> x
	Creation				=> paladin
	Destruction			=> paladin
	Protection		=> paladin
	Combat			=> paladin
	Travelers		=> x
	Divination 		=> paladin
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> paladin
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_paladin_inquisitor_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabpa03_spheres BEGIN
	Healing 		=> paladin
	Necromantic		=> x
	Creation				=> paladin
	Destruction			=> x
	Protection		=> paladin
	Combat			=> x
	Travelers		=> x
	Divination 		=> paladin
	Wards	 		=> x
	Thought 		=> paladin
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> paladin
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_paladin_undead_hunter_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabpa04_spheres BEGIN
	Healing 		=> paladin
	Necromantic		=> paladin
	Creation				=> paladin
	Destruction			=> x
	Protection		=> paladin
	Combat			=> paladin
	Travelers		=> x
	Divination 		=> paladin
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> paladin
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_fallen_paladin_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabpa05_spheres BEGIN
	Healing 		=> paladin
	Necromantic		=> x
	Creation				=> paladin
	Destruction			=> paladin
	Protection		=> paladin
	Combat			=> paladin
	Travelers		=> x
	Divination 		=> paladin
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> x
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> paladin
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_blackguard_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabpa06_spheres BEGIN
	Healing 		=> x
	Necromantic		=> paladin
	Creation				=> x
	Destruction			=> paladin
	Protection		=> x
	Combat			=> paladin
	Travelers		=> x
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> paladin
	Law	 			=> paladin
	Chaos	 		=> paladin
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> paladin
	Weather 		=> x
	Astral	    	=> paladin
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_ranger_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabrn01_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> ranger
	Combat			=> x
	Travelers		=> ranger
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> ranger
	Earth 			=> x
	Water 			=> x
	Air 			=> ranger
	Fire 			=> x
	Sun	 			=> ranger
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_ranger_archer_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabrn02_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> ranger
	Combat			=> x
	Travelers		=> ranger
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> ranger
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_ranger_stalker_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabrn03_spheres BEGIN
	Healing 		=> x
	Necromantic		=> x
	Creation				=> x
	Destruction			=> x
	Protection		=> x
	Combat			=> x
	Travelers		=> ranger
	Divination 		=> x
	Wards	 		=> ranger
	Thought 		=> ranger
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> ranger
	Fire 			=> x
	Sun	 			=> x
	Shadow 			=> ranger
	Weather 		=> x
	Astral	    	=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_ranger_beastmaster_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabrn04_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation		=> x
	Destruction			=> x
	Protection		=> ranger
	Combat			=> x
	Travelers		=> ranger
	Divination 		=> ranger
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 		=> ranger
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun	 		=> x
	Shadow 			=> x
	Weather 		=> x
	Astral	    	        => x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO vanilla_fallen_ranger_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabrn05_spheres BEGIN
	Healing 		=> ranger
	Necromantic		=> x
	Creation		=> x
	Destruction			=> x
	Protection 		=> x
	Combat			=> x
	Travelers		=> ranger
	Divination 		=> x
	Wards	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law	 			=> ranger
	Chaos	 		=> x
	Animal 			=> ranger
	Plant 			=> ranger
	Earth 			=> x
	Water 			=> x
	Air 			=> ranger
	Fire 			=> x
	Sun	 			=> ranger
	Shadow 			=> x
	Weather 		=> x
	Astral	     	=> x
 END
END
//___________________________________________________________________________________

// OTHER MOD KIT SPHERE ASSIGNMENTS__________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_cyric_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY a#cyric_spheres BEGIN
	Healing			=> minor
	Necromantic		=> major
	Creation 		 	=> minor
	Destruction		 	=> major
	Protection 		=> x
	Combat			=> x
	Travelers 	 	=> minor
	Divination 		=> x
	Wards 	 		=> major
	Thought 		=> minor
	Charm 			=> major
	Law  			=> minor
	Chaos 	 		=> major
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun  			=> x
	Shadow 			=> major
	Weather  		=> minor
	Astral 	 		=> major
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_corellon_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY a#feyw_spheres BEGIN
	Healing			=> major
	Necromantic		=> x
	Creation 		 	=> major
	Destruction		 	=> minor
	Protection 		=> major
	Combat			=> major
	Travelers 	 	=> major
	Divination 		=> major
	Wards 	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law  			=> minor
	Chaos 	 		=> x
	Animal 			=> x
	Plant 			=> major
	Earth 			=> x
	Water 			=> minor
	Air 			=> minor
	Fire 			=> x
	Sun  			=> major
	Shadow 			=> x
	Weather			=> minor
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_kossuth_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY a#koss_spheres BEGIN
	Healing			=> major
	Necromantic		=> minor
	Creation 		 	=> minor
	Destruction		 	=> major
	Protection 		=> major
	Combat			=> minor
	Travelers 	 	=> x
	Divination 		=> major
	Wards 	 		=> x
	Thought 		=> x
	Charm 			=> minor
	Law  			=> minor
	Chaos 	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> focus
	Sun  			=> major
	Shadow 			=> x
	Weather			=> minor
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_oghma_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY a#ogma_spheres BEGIN
	Healing			=> major
	Necromantic		=> minor
	Creation 		 	=> major
	Destruction		 	=> minor
	Protection 		=> major
	Combat			=> x
	Travelers 	 	=> minor
	Divination 		=> focus
	Wards 	 		=> minor
	Thought 		=> major
	Charm 			=> minor
	Law  			=> x
	Chaos 	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun  			=> minor
	Shadow 			=> minor
	Weather			=> major
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_oozemaster_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY a#ooze_spheres BEGIN
	Healing			=> major
	Necromantic		=> minor
	Creation 		 	=> x
	Destruction		 	=> x
	Protection 		=> x
	Combat			=> x
	Travelers 	 	=> minor
	Divination 		=> minor
	Wards 	 		=> x
	Thought 		=> minor
	Charm 			=> minor
	Law  			=> major
	Chaos 	 		=> major
	Animal 			=> x
	Plant 			=> major
	Earth 			=> major
	Water 			=> major
	Air 			=> minor
	Fire 			=> x
	Sun  			=> x
	Shadow 			=> minor
	Weather			=> x
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_redknight_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY a#red_spheres BEGIN
	Healing			=> minor
	Necromantic		=> minor
	Creation 		 	=> major
	Destruction		 	=> major
	Protection 		=> major
	Combat			=> major
	Travelers 	 	=> minor
	Divination 		=> minor
	Wards 	 		=> x
	Thought 		=> minor
	Charm 			=> major
	Law  			=> major
	Chaos 	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> minor
	Sun  			=> minor
	Shadow 			=> x
	Weather			=> x
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_shar_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY a#shar_spheres BEGIN
	Healing			=> minor
	Necromantic		=> major
	Creation 		 	=> x
	Destruction		 	=> major
	Protection 		=> minor
	Combat			=> x
	Travelers 	 	=> x
	Divination 		=> minor
	Wards 	 		=> minor
	Thought 		=> minor
	Charm 			=> major
	Law  			=> x
	Chaos 	 		=> minor
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun  			=> x
	Shadow 			=> major
	Weather			=> major
	Astral 	 		=> major
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_tempus_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY a#temp_spheres BEGIN
	Healing			=> major
	Necromantic		=> x
	Creation 		 	=> major
	Destruction		 	=> major
	Protection 		=> major
	Combat			=> major
	Travelers 	 	=> minor
	Divination 		=> minor
	Wards 	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law  			=> major
	Chaos 	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> minor
	Water 			=> x
	Air 			=> minor
	Fire 			=> x
	Sun  			=> minor
	Shadow 			=> x
	Weather			=> minor
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_ilmater_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY cdilmatr_spheres BEGIN
	Healing			=> major
	Necromantic		=> x
	Creation 		 	=> major
	Destruction		 	=> minor
	Protection 		=> major
	Combat			=> x
	Travelers 	 	=> x
	Divination 		=> major
	Wards 	 		=> x
	Thought 		=> minor
	Charm 			=> minor
	Law  			=> major
	Chaos 	 		=> major
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun  			=> minor
	Shadow 			=> x
	Weather			=> minor
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_selune_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY cdselune_spheres BEGIN
	Healing			=> major
	Necromantic		=> x
	Creation 		 	=> major
	Destruction		 	=> x
	Protection 		=> major
	Combat			=> minor
	Travelers 	 	=> minor
	Divination 		=> major
	Wards 	 		=> minor
	Thought 		=> major
	Charm 			=> x
	Law  			=> minor
	Chaos 	 		=> minor
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> major
	Fire 			=> x
	Sun  			=> major
	Shadow 			=> minor
	Weather			=> minor
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_xvim_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY cdxvim_spheres BEGIN
	Healing			=> minor
	Necromantic		=> major
	Creation 		 	=> major
	Destruction		 	=> major
	Protection 		=> x
	Combat			=> major
	Travelers 	 	=> x
	Divination 		=> minor
	Wards 	 		=> x
	Thought 		=> minor
	Charm 			=> major
	Law  			=> minor
	Chaos 	 		=> major
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun  			=> x
	Shadow 			=> minor
	Weather			=> minor
	Astral 	 		=> major
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_sune_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY nmsune_spheres BEGIN
	Healing			=> major
	Necromantic		=> x
	Creation 		 	=> major
	Destruction		 	=> x
	Protection 		=> minor
	Combat			=> x
	Travelers 	 	=> minor
	Divination 		=> major
	Wards 	 		=> major
	Thought 		=> major
	Charm 			=> major
	Law  			=> major
	Chaos 	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun  			=> minor
	Shadow 			=> minor
	Weather			=> minor
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_wildrunner_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY nmrnwlrn_spheres BEGIN
	Healing			=> ranger
	Necromantic		=> x
	Creation 		 	=> x
	Destruction		 	=> x
	Protection 		=> x
	Combat			=> x
	Travelers 	 	=> ranger
	Divination 		=> x
	Wards 	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law  			=> ranger
	Chaos 	 		=> x
	Animal 			=> ranger
	Plant 			=> ranger
	Earth 			=> x
	Water 			=> x
	Air 			=> ranger
	Fire 			=> x
	Sun  			=> ranger
	Shadow 			=> x
	Weather			=> x
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_bowslinger_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY nmrnbsln_spheres BEGIN
	Healing			=> ranger
	Necromantic		=> x
	Creation 		 	=> x
	Destruction		 	=> x
	Protection 		=> x
	Combat			=> x
	Travelers 	 	=> ranger
	Divination 		=> x
	Wards 	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law  			=> ranger
	Chaos 	 		=> x
	Animal 			=> ranger
	Plant 			=> ranger
	Earth 			=> x
	Water 			=> x
	Air 			=> ranger
	Fire 			=> x
	Sun  			=> ranger
	Shadow 			=> x
	Weather			=> x
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_feralan_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY a#feral_spheres BEGIN
	Healing			=> ranger
	Necromantic		=> x
	Creation 		 	=> x
	Destruction		 	=> x
	Protection 		=> x
	Combat			=> x
	Travelers 	 	=> ranger
	Divination 		=> x
	Wards 	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law  			=> ranger
	Chaos 	 		=> x
	Animal 			=> ranger
	Plant 			=> ranger
	Earth 			=> x
	Water 			=> x
	Air 			=> ranger
	Fire 			=> x
	Sun  			=> ranger
	Shadow 			=> x
	Weather			=> x
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_forrunner_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY nmrnfrrn_spheres BEGIN
	Healing			=> ranger
	Necromantic		=> x
	Creation 		 	=> x
	Destruction		 	=> x
	Protection 		=> x
	Combat			=> x
	Travelers 	 	=> ranger
	Divination 		=> x
	Wards 	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law  			=> ranger
	Chaos 	 		=> x
	Animal 			=> ranger
	Plant 			=> ranger
	Earth 			=> x
	Water 			=> x
	Air 			=> ranger
	Fire 			=> x
	Sun  			=> ranger
	Shadow 			=> x
	Weather			=> x
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO DR_justifier_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY a#justif_spheres BEGIN
	Healing			=> ranger
	Necromantic		=> x
	Creation 		 	=> x
	Destruction		 	=> x
	Protection 		=> x
	Combat			=> x
	Travelers 	 	=> x
	Divination 		=> x
	Wards 	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law  			=> ranger
	Chaos 	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun  			=> ranger
	Shadow 			=> x
	Weather			=> x
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO FJ_auril_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabauri_spheres BEGIN
	Healing			=> minor
	Necromantic		=> minor
	Creation 		 	=> major
	Destruction		 	=> major
	Protection 		=> major
	Combat			=> minor
	Travelers 	 	=> x
	Divination 		=> major
	Wards 	 		=> x
	Thought 		=> minor
	Charm 			=> major
	Law  			=> x
	Chaos 	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> major
	Air 			=> x
	Fire 			=> x
	Sun  			=> x
	Shadow 			=> minor
	Weather			=> minor
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO FJ_ulutiu_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabiceg_spheres BEGIN
	Healing			=> major
	Necromantic		=> x
	Creation 		 	=> major
	Destruction		 	=> x
	Protection 		=> major
	Combat			=> minor
	Travelers 	 	=> major
	Divination 		=> minor
	Wards 	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law  			=> major
	Chaos 	 		=> x
	Animal 			=> major
	Plant 			=> x
	Earth 			=> x
	Water 			=> focus
	Air 			=> minor
	Fire 			=> x
	Sun  			=> minor
	Shadow 			=> minor
	Weather			=> x
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO FJ_earth_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabeart_spheres BEGIN
	Healing			=> major
	Necromantic		=> minor
	Creation 		 	=> minor
	Destruction		 	=> major
	Protection 		=> minor
	Combat			=> minor
	Travelers 	 	=> x
	Divination 		=> major
	Wards 	 		=> x
	Thought 		=> minor
	Charm 			=> major
	Law  			=> major
	Chaos 	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> focus
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun  			=> x
	Shadow 			=> x
	Weather			=> minor
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO FJ_leaftender_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clableaf_spheres BEGIN
	Healing			=> major
	Necromantic		=> x
	Creation 		 	=> major
	Destruction		 	=> x
	Protection 		=> major
	Combat			=> x
	Travelers 	 	=> major
	Divination 		=> minor
	Wards 	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law  			=> major
	Chaos 	 		=> x
	Animal 			=> x
	Plant 			=> major
	Earth 			=> minor
	Water 			=> minor
	Air 			=> minor
	Fire 			=> x
	Sun  			=> major
	Shadow 			=> minor
	Weather			=> x
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO FJ_treetender_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabtree_spheres BEGIN
	Healing			=> major
	Necromantic		=> x
	Creation 		 	=> major
	Destruction		 	=> x
	Protection 		=> minor
	Combat			=> x
	Travelers 	 	=> major
	Divination 		=> minor
	Wards 	 		=> x
	Thought 		=> minor
	Charm 			=> x
	Law  			=> major
	Chaos 	 		=> x
	Animal 			=> x
	Plant 			=> major
	Earth 			=> major
	Water 			=> minor
	Air 			=> minor
	Fire 			=> x
	Sun  			=> major
	Shadow 			=> minor
	Weather			=> x
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO FJ_gruumsh_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabgruu_spheres BEGIN
	Healing			=> minor
	Necromantic		=> minor
	Creation 		 	=> minor
	Destruction		 	=> major
	Protection 		=> minor
	Combat			=> major
	Travelers 	 	=> x
	Divination 		=> x
	Wards 	 		=> x
	Thought 		=> x
	Charm 			=> major
	Law  			=> major
	Chaos 	 		=> major
	Animal 			=> minor
	Plant 			=> x
	Earth 			=> major
	Water 			=> x
	Air 			=> x
	Fire 			=> minor
	Sun  			=> x
	Shadow 			=> x
	Weather			=> x
	Astral 	 		=> major
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO FJ_luthic_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY clabluth_spheres BEGIN
	Healing			=> major
	Necromantic		=> major
	Creation 		 	=> minor
	Destruction		 	=> major
	Protection 		=> major
	Combat			=> minor
	Travelers 	 	=> x
	Divination 		=> major
	Wards 	 		=> x
	Thought 		=> minor
	Charm 			=> major
	Law  			=> minor
	Chaos 	 		=> minor
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun  			=> x
	Shadow 			=> x
	Weather			=> minor
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO FJ_hivemaster_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY k9hive_spheres BEGIN
	Healing			=> major
	Necromantic		=> x
	Creation 		 	=> x
	Destruction		 	=> x
	Protection 		=> x
	Combat			=> x
	Travelers 	 	=> x
	Divination 		=> minor
	Wards 	 		=> x
	Thought 		=> minor
	Charm 			=> minor
	Law  			=> major
	Chaos 	 		=> major
	Animal 			=> major
	Plant 			=> major
	Earth 			=> minor
	Water 			=> minor
	Air 			=> major
	Fire 			=> x
	Sun  			=> x
	Shadow 			=> minor
	Weather			=> x
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO FJ_palilmater_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY k9ilma_spheres BEGIN
	Healing			=> paladin
	Necromantic		=> x
	Creation 		 	=> paladin
	Destruction		 	=> paladin
	Protection 		=> paladin
	Combat			=> x
	Travelers 	 	=> x
	Divination 		=> paladin
	Wards 	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law  			=> paladin
	Chaos 	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun  			=> x
	Shadow 			=> x
	Weather			=> x
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO FJ_palmielikki_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY k9miel_spheres BEGIN
	Healing			=> paladin
	Necromantic		=> x
	Creation 		 	=> paladin
	Destruction		 	=> x
	Protection 		=> paladin
	Combat			=> x
	Travelers 	 	=> paladin
	Divination 		=> paladin
	Wards 	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law  			=> x
	Chaos 	 		=> x
	Animal 			=> paladin
	Plant 			=> paladin
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun  			=> x
	Shadow 			=> x
	Weather			=> x
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO fj_palmystra_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY k9myst_spheres BEGIN
	Healing			=> paladin
	Necromantic		=> x
	Creation 		 	=> paladin
	Destruction		 	=> paladin
	Protection 		=> paladin
	Combat			=> paladin
	Travelers 	 	=> x
	Divination 		=> paladin
	Wards 	 		=> x
	Thought 		=> x
	Charm 			=> x
	Law  			=> x
	Chaos 	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun  			=> x
	Shadow 			=> x
	Weather			=> paladin
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

// ________________________________________________________________
//
DEFINE_ACTION_MACRO sirene_ilmater_spheres BEGIN
 ACTION_DEFINE_ASSOCIATIVE_ARRAY c0ilmcl_spheres BEGIN
	Healing			=> paladin
	Necromantic		=> x
	Creation 		=> paladin
	Destruction		 	=> X
	Protection 		=> paladin
	Combat			=> x
	Travelers 	 	=> x
	Divination 		=> paladin
	Wards 	 		=> x
	Thought 		=> x
	Charm 			=> paladin
	Law  			=> paladin
	Chaos 	 		=> x
	Animal 			=> x
	Plant 			=> x
	Earth 			=> x
	Water 			=> x
	Air 			=> x
	Fire 			=> x
	Sun  			=> x
	Shadow 			=> x
	Weather			=> x
	Astral 	 		=> x
 END
END
//___________________________________________________________________________________

